Refactor the CI script to use inclusion instead of exclusion
easybuilders/easybuild-framework pull request #3616
Opened 2021-03-18 10:28 UTC by Flamefire

This provides more clarity on what exactly is run

The jobs have not changed, the following configurations are tested before (and after):
```
build (2.7, Lmod-7.8.22, Lua)
build (2.7, Lmod-7.8.22, Tcl)
build (2.7, Lmod-8.2.9, Lua)
build (2.7, Lmod-8.2.9, Tcl)
build (2.7, modules-tcl-1.147, Tcl)
build (2.7, modules-3.2.10, Tcl)
build (2.7, modules-4.1.4, Tcl)

build (3.6, Lmod-7.8.22, Lua)
build (3.6, Lmod-7.8.22, Tcl)
build (3.6, Lmod-8.2.9, Lua)
build (3.6, Lmod-8.2.9, Tcl)
build (3.6, modules-tcl-1.147, Tcl)
build (3.6, modules-3.2.10, Tcl)
build (3.6, modules-4.1.4, Tcl)

build (3.5, Lmod-8.2.9, Lua)
build (3.5, Lmod-8.2.9, Tcl)

build (3.7, Lmod-8.2.9, Lua)
build (3.7, Lmod-8.2.9, Tcl)

build (3.8, Lmod-8.2.9, Lua)
build (3.8, Lmod-8.2.9, Tcl)

build (3.9, Lmod-8.2.9, Lua)
build (3.9, Lmod-8.2.9, Tcl)

build (3.6, Lmod-8.2.9, Lua, C)
```

2021-03-18 16:56 UTC, boegel submitted a review, later dismissed
@Flamefire lgtm, that looks a bit cleaner indeed.
Let's bump to the latest Lmod 8.x while we're at it: https://github.com/Flamefire/easybuild-framework/pull/7

2021-03-18 18:41 UTC, Flamefire commented
I'd like to try something more: Avoid the repetition of the lmod version.
It seems you can generate a whole matrix from within a job step: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#example-returning-a-json-object

But what we just need here is something we can access with `${{}}`, e.g. an env variable. I'll try that later, so marking this as a draft

2021-03-18 21:34 UTC, boegel commented
> I'd like to try something more: Avoid the repetition of the lmod version.
> It seems you can generate a whole matrix from within a job step: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#example-returning-a-json-object
> 
> But what we just need here is something we can access with `${{}}`, e.g. an env variable.
> I'll try that later, so hold up the merge please :)

OK! :)

2021-03-19 07:33 UTC, boegel commented
@Flamefire Once you're happy with the changes, I'll need to re-configure the test configurations that are required to pass (which is why there's a bunch of orange dots sitting there "waiting" right now).

2021-03-19 11:30 UTC, Flamefire commented
I think this works now. What do you think about this approach?
Alternative:
```
env:
  LMOD_7: Lmod-...
  ...
  modules_tool: [${env.LMOD_7}, ...]
```
That's a bit shorter but sets those as actual env variables, so my current approach feels "more right"

2021-03-22 08:26 UTC, boegel requested changes

2021-03-22 08:26 UTC, boegel commented on .github/workflows/unit_tests.yml
> +          - ${{needs.setup.outputs.lmod7}}
I think it doesn't hurt to add a comment here:

```
# use variables defined by 'setup' job above,
# see also https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context

2021-03-22 08:26 UTC, boegel commented on .github/workflows/unit_tests.yml
> +          # Test different Python versions with Lmod 8.x (with both Lua and Tcl module syntax)
```suggestion
          # Test different Python 3 versions with Lmod 8.x (with both Lua and Tcl module syntax)
```

2021-03-22 08:54 UTC, boegel approved these changes
lgtm

2021-03-31 16:53 UTC, merged