add deprecation warning for patches without .patch suffix
easybuilders/easybuild-framework pull request #3920
Opened 2021-12-28 14:31 UTC by smoors

fixes #3688

2022-01-04 19:40 UTC, boegel requested changes

2022-01-04 19:40 UTC, boegel commented on easybuild/tools/filetools.py
> +                            "path to where non-patch file should be copied: %s" % patch_spec, '5.0')
@smoors I would tweak this a bit, to have a cleaner deprecation warning message, see https://github.com/boegel/easybuild-framework/commit/0764aeb7ef4e0c874ae30ed2f2e5e13a0742dc5f

2022-01-10 13:38 UTC, ocaisa approved these changes

2022-01-10 13:39 UTC, ocaisa commented
@boegel This looks ok to me, I leave it to you to merge since you already reviewed it

2022-01-10 14:02 UTC, boegel approved these changes

2022-01-10 14:02 UTC, merged