Adds nvompi toolchain. The idea is to replicate what gompi/foss/GCC(core) do
easybuilders/easybuild-framework pull request #3969
Opened 2022-02-22 11:16 UTC by robert-mijakovic

(created using `eb --new-pr`)

2022-03-01 19:32 UTC, boegel approved these changes
lgtm

2022-03-01 22:04 UTC, boegel requested changes

2022-03-01 22:04 UTC, boegel commented on easybuild/toolchains/nvompi.py
> +:author: Bart Oldeman (McGill University, Calcul Quebec, Compute Canada)
@robert-mijakovic Please change author to yourself?

2022-04-12 07:32 UTC, ocaisa commented
@robert-mijakovic This looks good to merge, just need to address the comment

2022-04-12 16:00 UTC, robert-mijakovic commented
> @robert-mijakovic This looks good to merge, just need to address the comment

Done. Thanks for reminding me.

2022-04-27 07:40 UTC, boegel approved these changes
lgtm

2022-04-27 13:51 UTC, merged