Adds nvpsmpi toolchain. The idea is to replicate what gompi/foss/GCC(core) do.
easybuilders/easybuild-framework pull request #3970
Opened 2022-02-22 11:17 UTC by robert-mijakovic

(created using `eb --new-pr`)

2022-03-01 19:32 UTC, boegel approved these changes
lgtm

2022-03-01 22:03 UTC, boegel requested changes

2022-03-01 22:03 UTC, boegel commented on easybuild/toolchains/nvpsmpi.py
> +:author: Sebastian Achilles (Forschungszentrum Juelich)
@robert-mijakovic This should be changed to mention yourself?

2022-03-01 22:03 UTC, boegel commented on easybuild/toolchains/nvpsmpi.py
> +EasyBuild support for npsmpi compiler toolchain (includes NVHPC and ParaStationMPI).
`npsmpi` should be `nvpsmpi`?

2022-04-12 07:32 UTC, ocaisa commented
@robert-mijakovic This looks good to merge, just need to address the comments

2022-04-27 07:40 UTC, boegel approved these changes
lgtm

2022-04-27 13:51 UTC, merged