add pre/post extension hook (triggered before/after individual extension installations)
easybuilders/easybuild-framework pull request #4193
Opened 2023-01-21 08:35 UTC by boegel

While adding `EXTENSION_INSTALL` to `HOOKS_NAMES`, I noticed that the list of hooks wasn't being printed in order of being triggered, so I fixed that too...

fixes #4191

2023-01-23 16:06 UTC, lexming reviewed
Looks good, my only concern is that `pre_extension_hook` and `pre_extensions_hook` are too similar. One typo and we will be executing code where we don't want to without any error. Following the name of the global, what about renaming `pre_extension_hook` to `pre_installextension_hook` ?

2023-02-15 16:43 UTC, lexming requested changes

2023-02-15 16:43 UTC, lexming commented on test/framework/options.py
> +            "	post_extensions_hook",
This test needs the name change as well
```suggestion
            "	pre_extensions_hook",
            "	pre_single_extension_hook",
            "	post_single_extension_hook",
            "	post_extensions_hook",
```

2023-02-25 17:27 UTC, boegel commented on test/framework/options.py
> +            "	post_extensions_hook",
fixed in 6a46414a8 (with force push)

2023-02-26 10:02 UTC, lexming approved these changes
LGTM

2023-02-26 10:02 UTC, lexming commented
Going in, thanks @boegel !

2023-02-26 10:02 UTC, merged