enhance `Toolchain.get_flag` to handle lists
easybuilders/easybuild-framework pull request #4319
Opened 2023-08-09 15:48 UTC by branfosj

Alternative to #4318

2023-08-09 16:20 UTC, boegel commented
@branfosj Are you up for implementing a test for `get_flag` in `test/framework/toolchain.py` to confirm this is working as designed now for both string and list inputs? It looks like we don't have any yet...

2023-08-09 16:21 UTC, boegel requested changes

2023-08-09 17:26 UTC, branfosj commented on easybuild/tools/toolchain/toolchain.py
> +        if isinstance(self.options.option(name), list):
No. That will require more investigation as I'm getting the following error if I try to add that:
```
TypeError: 'tuple' object does not support item assignment
```

2023-08-09 17:36 UTC, branfosj commented on easybuild/tools/toolchain/toolchain.py
> +        if isinstance(self.options.option(name), list):
The full traceback after I added `or isinstance(self.options.option(name), tuple)` to the above and have `'-foo -bar': ('foo', 'bar'),` in the tests.

```
Traceback (most recent call last):
  File "/home/simon/work/easybuild-framework/test/framework/toolchain.py", line 2969, in test_get_flag
    self.assertEqual(tc.get_flag('openmp'), flagstring)
  File "/home/simon/work/easybuild-framework/easybuild/tools/toolchain/toolchain.py", line 1133, in get_flag
    if isinstance(self.options.option(name), list) or isinstance(self.options.option(name), tuple):
  File "/home/simon/work/easybuild-framework/easybuild/tools/toolchain/options.py", line 118, in option
    res[idx] = elem % templatedict
TypeError: 'tuple' object does not support item assignment
```

2023-08-10 07:16 UTC, branfosj commented on easybuild/tools/toolchain/toolchain.py
> +        if isinstance(self.options.option(name), list):
If I set `self.options.options_map['openmp'] = ('fiopenmp', )` and try a build I get
```
ERROR: Traceback (most recent call last):
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/main.py", line 133, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/framework/easyblock.py", line 4236, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/framework/easyblock.py", line 4119, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/framework/easyblock.py", line 3954, in run_step
    step_method(self)()
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/framework/easyblock.py", line 2667, in prepare_step
    rpath_include_dirs=self.rpath_include_dirs)
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/tools/toolchain/toolchain.py", line 859, in prepare
    self.set_variables()
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/toolchains/iimpi.py", line 108, in set_variables
    IntelCompilersToolchain.set_variables(self)
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/toolchains/compiler/intel_compilers.py", line 123, in set_variables
    Compiler.set_variables(self)
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/tools/toolchain/compiler.py", line 174, in set_variables
    self._set_compiler_flags()
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/tools/toolchain/compiler.py", line 250, in _set_compiler_flags
    flags = [self.options.option(x) for x in self.COMPILER_FLAGS if self.options.get(x, False)]
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/tools/toolchain/compiler.py", line 250, in <listcomp>
    flags = [self.options.option(x) for x in self.COMPILER_FLAGS if self.options.get(x, False)]
  File "/rds/projects/2017/branfosj-rse/easybuild/src/easybuild-framework/easybuild/tools/toolchain/options.py", line 115, in option
    res[idx] = elem % templatedict
TypeError: 'tuple' object does not support item assignment
```

That is before I get to `get_flag`. So there is further work to be done to support tuples at all. I consider that out of scope for this PR.

2023-08-10 12:44 UTC, ocaisa commented on easybuild/tools/toolchain/toolchain.py
> +        if isinstance(self.options.option(name), list):
Ok, agreed

2023-08-10 12:59 UTC, ocaisa approved these changes
LGTM

2023-08-10 13:00 UTC, merged