use more granular exit codes when `EasyBuildError` is raised
easybuilders/easybuild-framework pull request #4534
Opened 2024-05-16 15:57 UTC by dagonzalezfo

#4426 
This PR will provide a basic set of error codes for EB. The included ones can be classified in 2 groups 
-  Eb proper codes: 
     - 3: Missing easyconfig
     - 4: No specific easyblock
     - 5: Failed to import easyblock
     - 6: Failed to  import class from easyblock
     - 7: No recipe for dependency (robot)
     - 8: Os dependency missing
     - 9: Unavailable sources
     - 10: Sanity check folder/file
     - 11: Can not write module at modules path
     - 12: Validate errors (this is more focus on syntax)
- Other error codes: 
    - HTTP: Errors for fetching sources
    - system error codes for system calls
    - LMOD: Errors for loading module

2024-06-11 00:21 UTC, lexming requested changes
I tested this PR and went ahead expanding it to cover more errors. I also created a new `Enum` class to gather the table of exit codes.

Please check PR https://github.com/dagonzalezfo/easybuild-framework/pull/1 and specifically commit https://github.com/dagonzalezfo/easybuild-framework/commit/0d31d34cb5807dd485daf349c847b41f59ce2052 with my proposed changes.

One needed change is that EasyBuild cannot forward any exit codes from HTTP requests, or from external processes, as those can be out of range (3, 128) or have the same value as the custom exit codes of EB, which would be confusing. EasyBuild should always return its own exit codes and HTTP responses or exit codes from external processes should be reported in the logs.

Example behaviour with my PR:
```
$ eb zlib-1.2.13-GCCcore-12.3.0.eb
[...]
== configuring...
  >> running shell command:
        potato --prefix=/home/lexming/easybuild/install/software/zlib/1.2.13-GCCcore-12.3.0
        [started at: 2024-06-11 01:51:20]
        [working dir: /home/lexming/.local/easybuild/build/zlib/1.2.13/GCCcore-12.3.0/zlib-1.2.13]
        [output and state saved to /tmp/eb-8b28i2tz/run-shell-cmd-output/potato-coba1es3]

ERROR: Shell command failed!
    full command              ->  potato --prefix=/home/lexming/easybuild/install/software/zlib/1.2.13-GCCcore-12.3.0
    exit code                 ->  127
    working directory         ->  /home/lexming/.local/easybuild/build/zlib/1.2.13/GCCcore-12.3.0/zlib-1.2.13
    output (stdout + stderr)  ->  /tmp/eb-8b28i2tz/run-shell-cmd-output/potato-coba1es3/out.txt
    called from               ->  'configure_step' function in /home/lexming/.local/venv/eb/lib64/python3.10/site-packages/easybuild/easyblocks/generic/configuremake.py (line 326)

== ... (took < 1 sec)
== FAILED: Installation ended unsuccessfully: shell command 'potato ...' failed with exit code 127 in configure step for zlib-1.2.13-GCCcore-12.3.0.eb (took 0 secs)
== Results of the build can be found in the log file(s) /tmp/eb-8b28i2tz/easybuild-zlib-1.2.13-20240611.015120.QzdZC.log
ERROR: Installation of zlib-1.2.13-GCCcore-12.3.0.eb failed: "shell command 'potato ...' failed with exit code 127 in configure step for zlib-1.2.13-GCCcore-12.3.0.eb"
$ echo $?
15
```

2024-08-02 18:05 UTC, lexming commented
@hvelab printing HTTP error codes in warning messages or the logs (which is what that code snippet does) is fine. What is wrong is to use those as exit code for EB as those can easily be out of range  (3, 128). This is why I changed the exit code for EB in that case to well-defined `EasyBuildExit.FAIL_DOWNLOAD`. See a few lines further:

https://github.com/dagonzalezfo/easybuild-framework/blob/0d31d34cb5807dd485daf349c847b41f59ce2052/easybuild/tools/filetools.py#L847

2024-08-05 12:39 UTC, hvelab commented
@lexming Great! Then, is there something left to do with this PR from Danilo's help? Please let us know if we can help in any way in your enhancement

2024-08-19 10:06 UTC, boegel commented
@hvelab We need to get https://github.com/dagonzalezfo/easybuild-framework/pull/1 merged, which will update this PR.

@lexming I think we can do this without having @dagonzalezfo around though?

2024-08-19 11:16 UTC, dagonzalezfo commented
Hi, I will take care of it along this week :)

2024-08-20 10:52 UTC, dagonzalezfo commented
Dear @lexming , @boegel, @hvelab ,

I just accept all the changes proposed by Alex, do minimal style fixes and update the PR. 

If it needs futher work, just let me know.

2024-09-02 12:47 UTC, lexming submitted a review, later dismissed
LGTM

2024-09-02 13:26 UTC, dagonzalezfo commented
Dear @lexming, thanks for your help with it

2024-09-09 15:20 UTC, boegel commented on easybuild/tools/github.py
> +            "No changed files found when comparing to current develop branch. Refused to make empty pull request.",
While we're at it: `develop` shouldn't be hardcoded here:
```suggestion
            f"No changed files found when comparing to current {start_branch} branch. "
            "Refused to make empty pull request.",
```

2024-09-09 15:23 UTC, boegel commented on easybuild/tools/github.py
> +                "No changes in '%s' branch compared to current 'develop' branch!", branch_name,
shouldn't be hardcoded `develop` here either:
```suggestion
                f"No changes in '{branch_name}' branch compared to current '{pr_target_branch}' branch!",

2024-09-09 15:24 UTC, boegel commented on easybuild/tools/github.py
> +        raise EasyBuildError("Couldn't find any EasyBuild easyconfigs", exit_code=EasyBuildExit.MISS_EASYCONFIG)
```suggestion
        raise EasyBuildError("Couldn't find any EasyBuild easyconfigs", exit_code=EasyBuildExit.MISSING_EASYCONFIG)

2024-09-09 15:26 UTC, boegel commented on easybuild/tools/options.py
> +                            exit_code=EasyBuildExit.OPTION_ERROR
```suggestion
                            compiler, self.options.optarch, exit_code=EasyBuildExit.OPTION_ERROR

2024-09-09 15:26 UTC, boegel commented on easybuild/tools/options.py
> +                exit_code=EasyBuildExit.OPTION_ERROR
```suggestion
                VALID_CLOSE_PR_REASONS.keys(), exit_code=EasyBuildExit.OPTION_ERROR

2024-09-09 15:27 UTC, boegel commented on easybuild/tools/options.py
> +                    exit_code=EasyBuildExit.MISS_EB_DEPENDENCY
```suggestion
                    exit_code=EasyBuildExit.MISSING_EB_DEPENDENCY

2024-09-09 15:28 UTC, boegel commented on easybuild/tools/options.py
> +                    exit_code=EasyBuildExit.MISS_EB_DEPENDENCY
```suggestion
                    exit_code=EasyBuildExit.MISSING_EB_DEPENDENCY

2024-09-12 14:25 UTC, lexming commented on easybuild/framework/easyblock.py
> +                            "Couldn't find file %s anywhere, and downloading it is disabled... "
sure, done in https://github.com/easybuilders/easybuild-framework/pull/4534/commits/151b95919b490baadec6c021e8e00b18ad08b655

2024-09-17 11:31 UTC, lexming commented on easybuild/framework/easyblock.py
> +        exit_code = EasyBuildExit.SUCCESS
done in https://github.com/easybuilders/easybuild-framework/pull/4534/commits/60e06ce360b82120a94a6bca5022fb9486c60b7b

2024-09-17 11:57 UTC, lexming commented on easybuild/tools/build_log.py
> +            self.__dict__.update(kwargs)
this is indeed weird, changed in https://github.com/easybuilders/easybuild-framework/pull/4534/commits/a5e805abcada75cbe369ae4fb019c18fbb4b8954

2024-09-17 14:47 UTC, lexming approved these changes
LGTM

2024-09-18 12:48 UTC, boegel commented
Thanks a lot for all the effort on this @dagonzalezfo and @lexming!

2024-09-18 12:48 UTC, merged