Add capability to export rpath wrappers for a toolchain
easybuilders/easybuild-framework pull request #4596
Opened 2024-08-05 11:35 UTC by ocaisa

Based off of https://github.com/easybuilders/easybuild-framework/pull/4003

2025-03-14 08:39 UTC, ocaisa commented on easybuild/tools/toolchain/toolchain.py
> +                               add_to_path=True, disable_wrapper_log=False):
I need to rethink this slightly. I think a better approach is to have a build option `rpath_wrappers_dir` and drop these new arguments.

2025-03-17 11:13 UTC, ocaisa commented
This feature has been tested for EB 5 via https://github.com/easybuilders/easybuild-easyblocks/pull/3661

2025-03-19 10:56 UTC, boegel commented
@ocaisa I changed to target branch in this PR from 5.0.x to develop, you should synchronize your PR branch with current develop branch (which has received a massive update after the release of EasyBuild v5.0.0, see https://github.com/easybuilders/easybuild-framework/pull/4825)

2025-04-02 09:07 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +                                      rpath_include_dirs=self.rpath_include_dirs,
The omission of this looks like a bug to me, but I can't be 100%

2025-04-02 09:09 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +                                      rpath_include_dirs=self.rpath_include_dirs,
It probably doesn't actually matter as the wrappers will already have been prepared by the time this is called by an extension.

2025-04-23 07:28 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +                                      rpath_include_dirs=self.rpath_include_dirs,
(see https://github.com/easybuilders/easybuild-framework/pull/4596/files#diff-c1bad9950fee9f74b59e255119ea04ce41e9d9ce8cfa9fa94e831c8d314d106dR1041)

2025-04-23 08:56 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +        self.rpath_wrappers_dir = build_option('rpath_wrappers_dir')
This build option should only be set on the command line, it should _not_ be part of the configuration or an environment variable. This is because if you did that the wrappers would never get re-created. I'm not sure how to enforce this.

Another option would be to empty the directory within the next `if` block by default.

2025-04-23 09:09 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +        self.rpath_wrappers_dir = build_option('rpath_wrappers_dir')
Hmm, I think I might be wrong here, it looks like the default behaviour is indeed to always overwrite any existing wrappers: https://github.com/easybuilders/easybuild-framework/pull/4596/files#diff-c1bad9950fee9f74b59e255119ea04ce41e9d9ce8cfa9fa94e831c8d314d106dR1074

2025-04-23 09:11 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +        self.rpath_wrappers_dir = build_option('rpath_wrappers_dir')
The only condition that would protect against this is https://github.com/easybuilders/easybuild-framework/pull/4596/files#diff-c1bad9950fee9f74b59e255119ea04ce41e9d9ce8cfa9fa94e831c8d314d106dR1055 and this is not triggered as the updates to `PATH` are not in place until later.

2025-04-23 09:13 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +        self.rpath_wrappers_dir = build_option('rpath_wrappers_dir')
I can add a check there to warn or error (or just log?) that the existing wrappers will be overwritten.

2025-04-23 12:55 UTC, boegel commented on easybuild/framework/easyblock.py
> +                                      rpath_include_dirs=self.rpath_include_dirs,
It has no impact for 2nd extension, where we'll pick up on wrapper created for first extension.

But the RPATH wrapper that was created for the "parent" will no longer be found (because the build environment is reset before build environment for first extension is set up), and so the installation of extensions will be done with an incorrect RPATH wrapper script in which `rpath_include_dirs` is not picked up.

That's bad since `$ORIGIN/../lib` & co are specified that way (see how `self.rpath_wrappers_dir` is defined in `EasyBlock.prepare_step`).

2025-04-23 12:57 UTC, boegel commented on easybuild/framework/easyblock.py
> +                                      rpath_include_dirs=self.rpath_include_dirs,
Hold on, the resetting of build environment before starting installation of extensions is not correct I think, I'm going through things in detail now.

2025-04-23 13:03 UTC, boegel commented on easybuild/framework/easyblock.py
> +                                      rpath_include_dirs=self.rpath_include_dirs,
The `rpath_include_dirs` mechanism was implemented in #2358, which shows that it's only picked up by the "parent" `toolchain.prepare`, the call to `toolchain.prepare` for extensions was overlooked. That confirms to me this is a genuine bug.

I'm still a bit puzzled why this doesn't cause real trouble though, or how it has flown under the radar...

2025-04-23 13:34 UTC, boegel commented on easybuild/tools/options.py
> +            'rpath-wrappers-dir': ("Absolute path to directory to use for RPATH wrappers creation/use",
Rather than adding an EasyBuild configuration option for this, we can just only give control over through an easyblock which can set `self.rpath_wrappers_dir` in the constructor, so there's no control from the outside to tweak the location of the generaed RPATH wrapper scripts.

2025-04-23 17:06 UTC, boegel requested changes
@ocaisa Bunch of changes proposed for this PR in https://github.com/ocaisa/easybuild-framework/pull/47

2025-04-23 19:32 UTC, boegel approved these changes
lgtm

2025-04-23 19:34 UTC, merged