Rename SOURCE_STEP to EXTRACT_STEP
easybuilders/easybuild-framework pull request #4629
Opened 2024-09-11 15:03 UTC by Flamefire

Adjust tests to take that into account and add tests to check that the
old name causes a proper error.
Add such error handling for the `skipsteps` EC parameter.

Split up `test_skip` into more focused sub tests to allow adding the new (negative/failure) test of skipsteps to one of those.

Also a fix for `test_compiler_cache` and a bit cleanup to avoid copying the same superflous parameters in the new tests.

2024-09-11 19:48 UTC, boegel requested changes

2024-09-11 19:48 UTC, boegel commented on easybuild/framework/easyconfig/easyconfig.py
> +
To fix failing code style check:
```
./easybuild/framework/easyconfig/easyconfig.py:877:9: E303 too many blank lines (2)
```

```suggestion
```

2024-09-25 16:31 UTC, boegel commented
@Flamefire Merge conflict to fix, probably a trivial one...

2024-09-26 12:23 UTC, Flamefire commented
Jep, one of the test fixes I had opened a[ separate PR](https://github.com/easybuilders/easybuild-framework/pull/4599) for

2024-12-04 15:46 UTC, boegel approved these changes

2024-12-04 16:18 UTC, merged