[refactor:job_backend] Use Slurm as the default job back-end
easybuilders/easybuild-framework pull request #4659
Opened 2024-09-26 22:05 UTC by gkaf89

- The GC3Pie back-end for job management that has been the default so far is no longer actively supported. Use the Slurm back-end as default instead.
- Add deprecation message when the GC3Pie class is instantiated.

2024-09-27 06:14 UTC, boegel requested changes

2024-09-27 06:14 UTC, boegel commented on easybuild/tools/job/gc3pie.py
> +        _log.deprecated(deprication_msg, '5.0')
```suggestion
        deprecation_msg = "The GC3Pie job backend is no longer maintained and will be removed"
        deprecation_msg += ", please use a different job backend"
        _log.deprecated(deprecation_msg, '5.0')
```

2024-09-28 18:08 UTC, gkaf89 commented
There is a test that fails due to the deprecation message: 
```
test.framework.parallelbuild.ParallelBuildTest.test_build_easyconfigs_in_parallel_gc3pie
```

I manage to trace the issue in the deprecation message which is added in the GC3Pie constructor. During the tests the deprecation message in the log through an Exception; the test succeeds if the exception is caught. Under normal operation, logging the deprecation does not though an exception.

Is there any special handling of deprecation message logging in the tests?

2024-09-30 08:15 UTC, boegel commented
> Is there any special handling of deprecation message logging in the tests? How should I handle exceptions caused by deprecation messages in tests?

@gkaf89 Just call `self.allow_deprecated_behaviour()` in the test, there's a bunch of examples of this already in the test suite

2024-10-02 18:10 UTC, boegel approved these changes

2024-10-02 18:10 UTC, merged