Add `resolve_template` function to easyconfig instances
easybuilders/easybuild-framework pull request #4677
Opened 2024-10-10 16:07 UTC by Flamefire

(created using `eb --new-pr`)

2024-10-12 14:55 UTC, boegel requested changes
@Flamefire Can you look into adding a dedicated test for the `resolve_template` method?

2024-10-12 15:00 UTC, Flamefire commented
> @Flamefire Can you look into adding a dedicated test for the `resolve_template` method?

I though it was not necessary: The tests for checking the template values already cover this via the getters and a test if `ec.resolve_template(x) == resolve_template(x, ec.template_values)` doesn't seem to provide much value as that is basically the implementation of the method.

So only thing which I'd say is worth checking, is whether the template dict gets initialized first time this gets called to detect easier if it gets removed by some later change, although the other tests would fail already.   
But I'm not sure how to "legally" create an easyconfig instance without the template_values being initialized.

2024-10-14 14:55 UTC, Flamefire commented
I added a test and tried to trigger the case where `template_values` is not set. Turns out this is impossible, so I removed the condition.

2024-12-11 07:48 UTC, boegel requested changes

2024-12-11 07:48 UTC, boegel commented on easybuild/framework/easyconfig/easyconfig.py
> +        return resolve_template(value, self.template_values)
```suggestion
        if not self.template_values:
            self.generate_template_values()
        return resolve_template(value, self.template_values)
```

2024-12-11 07:50 UTC, boegel approved these changes
lgtm

2024-12-11 08:40 UTC, merged