simplify code for determining the PYTHONPATH module entries
easybuilders/easybuild-framework pull request #4686
Opened 2024-10-20 14:45 UTC by Flamefire

The check whether the path(s) have already been added is redundant as that is done in the module_generator class.

The whole code with all the checks is superflous if there are no python paths to add.

To avoid excessive indentation return early with an empty list in that case and same for Python installations for consistency.

`prepend_paths` can return an empty string when everything is filtered. As we return a list here (we might be better of returning a string instead) return an empty list to avoid empty lines being written if `'\n'` was used. -> TODO for later

Best to view with whitespace changes ignored

2024-11-01 10:11 UTC, Micket commented
> The check whether the path(s) have already been added is redundant as that is done in the module_generator class.

which then also prints warnings, which i wanted to avoid

https://github.com/easybuilders/easybuild-framework/blob/b5c1dd97fd34bb15855783002b2874184f1987b1/easybuild/tools/module_generator.py#L231C1-L233C40

2024-11-08 12:31 UTC, Flamefire commented
> which then also prints warnings, which i wanted to avoid

Oh I see. I'd avoid to duplicate the logic though, see the new commit(s)

2024-11-15 16:14 UTC, Micket approved these changes
lgtm

2024-11-15 16:22 UTC, Micket requested changes
actually, while attempting to solve the merge conflict, I think we should also add the new warn_exists keyword to append_paths as well, to make them similar.

2024-11-18 15:04 UTC, Flamefire commented
Good point, rebased and implemented

2024-11-19 13:03 UTC, Micket approved these changes
lgtm

2024-11-22 14:06 UTC, merged