add a CUDA device code sanity check
easybuilders/easybuild-framework pull request #4692
Opened 2024-10-24 16:53 UTC by jfgrimm

At the moment, we do no checking that the cuda compute capabilities that EasyBuild is configured to use, are actually used in the resultant binaries/libraries

WIP PR to introduce an extra sanity check when CUDA is present to check for mismatches between `cuda_compute_capabilities` and what `cuobjdump` reports

2024-10-24 17:17 UTC, ocaisa commented
It's great that you looked into this, we've also been discussing it in EESSI: https://gitlab.com/eessi/support/-/issues/92

2024-10-24 17:32 UTC, jfgrimm commented
@ocaisa thanks for the link, I'll take a look

Currently, main things I still plan to add to this pr:
* An EB option to toggle whether this is a warning or error (akin to rpath sanity check strictness)
* whitelisting (e.g. for bundled precompiled stuff)
* handling software that only allows targeting a single CCC

2024-10-24 17:41 UTC, ocaisa commented
I think it's a good idea to check for device code and ptx (with lack of ptx for the highest compute capability being a warning). The availability of ptx will allow you to run the application on future arch's.

2025-02-19 19:38 UTC, ocaisa commented on easybuild/tools/systemtools.py
> +    device_code_regex = re.compile('(?<=arch = sm_)([0-9])([0-9]+a{0,1})')
It would be to also capture whether the code can be jit compiled (so it can at least run on a future arch). In a script I had I did this with:
```
# Regex to find multiple PTX and ELF sections
        ptx_matches = re.findall(r'Fatbin ptx code:\n=+\narch = sm_(\d+)', result.stdout)
        elf_matches = re.findall(r'Fatbin elf code:\n=+\narch = sm_(\d+)', result.stdout)

        # Debug: Show if matches were found for PTX and ELF sections
        if debug:
            print(f"PTX Matches: {ptx_matches}")
            print(f"ELF Matches: {elf_matches}")

        # Return all PTX and ELF matches, remove duplicates using set and convert to lists
        return {
            "ptx": sorted(set(ptx_matches)),  # List of unique PTX capabilities
            "elf": sorted(set(elf_matches))   # List of unique ELF capabilities
        }
```

2025-02-19 19:45 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +        if get_software_root('CUDA'):
@boegel We have an EESSI-specific complication here. We drop CUDA to a build time dep so that we don't depend on the CUDA module at runtime. This means that we won't execute this code path so we need to trigger the module load here.

2025-02-19 19:48 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            self.log.info("Using default subdirectories for binaries/libraries to verify CUDA device code: %s",
This info message seems wrong: this is _not_ the default subdirectories, this is a customly defined `bin_lib_subdirs`

2025-02-19 20:17 UTC, casparvl commented
I tested this as follows:


- cloned Jasper's feature branch into `$HOME/easybuild/easybuild-framework/`
- load EESSI and EESSI-extend: `module purge && module load EESSI/2023.06 EESSI-extend/2023.06-easybuild`
- installed an EasyBuild from the current `5.0.x` branch using the EasyConfig `EasyBuild-5.0.x.eb` below, using the EasyBuild-4.9.4 from EESSI: `eb EasyBuild-5.0.x.eb`. This ensures I have the versions of blocks and easyconfigs from `5.0.x`.
```
#EasyBuild-5.0.x.eb
# Nice way of installing an EasyBuild installation from the develop branch...
# Install with 'eblocalinstall --force-download ...' to make sure you get the latest version
easyblock = 'EB_EasyBuildMeta'
name = 'EasyBuild'
version = '5.0.x'
homepage = 'https://easybuilders.github.io/easybuild'
description = """EasyBuild is a software build and installation framework
 written in Python that allows you to install software in a structured,
 repeatable and robust way."""
toolchain = SYSTEM
sources = [
    {
        'source_urls': ['https://github.com/easybuilders/easybuild-framework/archive/'],
        'download_filename': '5.0.x.tar.gz',
        'filename': 'easybuild-framework-develop.tar.gz',
    },
    {
        'source_urls': ['https://github.com/easybuilders/easybuild-easyblocks/archive/'],
        'download_filename': '5.0.x.tar.gz',
        'filename': 'easybuild-easyblocks-develop.tar.gz',
    },
    {
        'source_urls': ['https://github.com/easybuilders/easybuild-easyconfigs/archive/'],
        'download_filename': '5.0.x.tar.gz',
        'filename': 'easybuild-easyconfigs-develop.tar.gz',
    },
]
# order matters a lot, to avoid having dependencies auto-resolved (--no-deps easy_install option doesn't work?)
# EasyBuild is a (set of) Python packages, so it depends on Python
# usually, we want to use the system Python, so no actual Python dependency is listed
allow_system_deps = [('Python', SYS_PYTHON_VERSION)]
local_pyshortver = '.'.join(SYS_PYTHON_VERSION.split('.')[:2])
sanity_check_paths = {
    'files': ['bin/eb'],
    'dirs': ['lib/python%s/site-packages' % local_pyshortver],
}
moduleclass = 'tools'
```
- Set the folowing environment variables to pick up on the feature branch:
```
export PATH=$HOME/easybuild/easybuild-framework/:$PATH
export PYTHONPATH=$HOME/easybuild/easybuild-framework/:$PYTHONPATH
```
- Added the following configuration (for some reason, my robot-path was empty, I now make it use the easyconfigs from the 5.0.x I installed above):
```
export EASYBUILD_ROBOT_PATHS=/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/EasyBuild/5.0.x/easybuild/easyconfigs
export EASYBUILD_CUDA_COMPUTE_CAPABILITIES=8.0
```

- I tried to install a `CUDA-Samples`:
```
eb CUDA-Samples-12.1-GCC-12.3.0-CUDA-12.1.1.eb --rebuild
```

This resulted in 

```
== 2025-02-19 20:55:23,959 build_log.py:226 ERROR EasyBuild encountered an error (at easybuild/easybuild-framework/easybuild/tools/build_log.py:166 in caller_
info): Sanity check failed: Mismatch between cuda_compute_capabilities and device code in /home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/
software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/jitLto. Surplus compute capabilities: 5.2. Missing compute capabilities: 8.0.
Mismatch between cuda_compute_capabilities and device code in /home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-G
CC-12.3.0-CUDA-12.1.1/bin/inlinePTX_nvrtc. Surplus compute capabilities: 5.2. Missing compute capabilities: 8.0.
Mismatch between cuda_compute_capabilities and device code in /home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-G
CC-12.3.0-CUDA-12.1.1/bin/conjugateGradientCudaGraphs. Surplus compute capabilities: 5.0, 5.2, 6.0, 6.1, 7.0, 7.5, 8.6, 8.9, 9.0.
```

And many more. That's great, it means this PR is actually doing what it should. Indeed, checking manually:

```
$ cuobjdump /home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/jitLto

Fatbin elf code:
================
arch = sm_52
code version = [1,7]
host = linux
compile_size = 64bit
```

So, yeah... `CUDA-Samples` is a mess when it comes to it's build system. The docs say you can set the CUDA compute capabilities by passing the `SMS=<something>` argument to it. Just for reference, my build command from the logs was:

```
rm -r bin/win64 &&  make  -j 16 HOST_COMPILER=g++ SMS='80'
 FILTER_OUT='Samples/2_Concepts_and_Techniques/EGLStream_CUDA_Interop/Makefile Samples/2_Concepts_and_Techniques/streamOrderedAllocationIPC/Makefile Samples/3
_CUDA_Features/tf32TensorCoreGemm/Makefile Samples/3_CUDA_Features/warpAggregatedAtomicsCG/Makefile Samples/4_CUDA_Libraries/boxFilterNPP/Makefile Samples/4_C
UDA_Libraries/cannyEdgeDetectorNPP/Makefile Samples/4_CUDA_Libraries/cudaNvSci/Makefile Samples/4_CUDA_Libraries/cudaNvSciNvMedia/Makefile Samples/4_CUDA_Libr
aries/freeImageInteropNPP/Makefile Samples/4_CUDA_Libraries/histEqualizationNPP/Makefile Samples/4_CUDA_Libraries/FilterBorderControlNPP/Makefile Samples/5_Do
main_Specific/simpleGL/Makefile Samples/5_Domain_Specific/simpleVulkan/Makefile Samples/5_Domain_Specific/simpleVulkanMMAP/Makefile Samples/5_Domain_Specific/
vulkanImageCUDA/Makefile Samples/0_Introduction/simpleAWBarrier/Makefile Samples/3_CUDA_Features/bf16TensorCoreGemm/Makefile Samples/3_CUDA_Features/dmmaTenso
rCoreGemm/Makefile Samples/3_CUDA_Features/globalToShmemAsyncCopy/Makefile Samples/4_CUDA_Libraries/simpleCUFFT_callback/Makefile Samples/2_Concepts_and_Techn
iques/cuHook/Makefile ' && rm bin/*/linux/release/lib*.so.*
```
```
```

2025-02-19 20:44 UTC, casparvl commented
Collecting some todo's:

- [ ] add `--strict-cuda-sanity-check` EB option (default no): regular sanity check would fail (raise an error) if not _at least_ the configured CCs are present. It should report surplus CCs (at least with `--debug`), but not fail. The strict variant will also fail if there are surplus CCs present. N.B. I'm not in favor of converting the error into a warning here - if you're not getting the CC you're requesting via `--cuda-compute-capabilities`, that's _not_ what the user is counting on, and that should be a failure. A user can always decide to whitelist to make sure the sanity check passes, but this should be a very conscious decision. Since many of us are building in bulk, semi-automated pipelines, etc, warnings would too easily be missed.
- [ ] whitelisting (e.g. for bundled precompiled stuff). This will cause the sanity check to be skipped (or at most print a warning/info) for software that is whitelisted. It enables a conscious override by a user to say 'yes, I know this binary wasn't build for the requested CC, and I'm ok with that'.
- [ ] Also check for PTX code (and which arch that PTX code is for). We currently don't have any way of asking EasyBuild to build for a certain PTX arch, so a question would be: what do we check against? A logical default would be to check for PTX code for the _highest_ CC in `--cuda-compute-capabilities` as this would allow forward-compatibility of the binary through JIT compilation.
- [ ] add `--strict-cuda-ptx-check` (default: no): Check that PTX code is present for the highest CC in `--cuda-compute-capabilities` and if not, fail. Without this option, the PTX code will be checked, but if no PTX is present for the higest CC in `--cuda-compute-capabilities`, it will just print a warning / info message.

2025-02-19 20:48 UTC, casparvl commented on easybuild/framework/easyblock.py
> +        if get_software_root('CUDA'):
I think you're right, but just to double check: are the build dependencies unloaded at sanity check time?

Could we fix this through an EasyBuild hook in EESSI, that loads the CUDA that was a build dependency also in the sanity_check_step (and unloads after)? Should also work for `EESSI-extend`, and no changes on the framework side needed...

2025-02-19 20:58 UTC, casparvl commented on easybuild/tools/systemtools.py
> +    device_code_regex = re.compile('(?<=arch = sm_)([0-9])([0-9]+a{0,1})')
In fact: `re.compile('(?<=arch = sm_)([0-9])([0-9]+a{0,1})')` is not specific enough, because it will treat the `Fatbin ptx code` and `Fatbin elf code` sections the same: it'll just extract any `arch = ` string it can find.

To have a concrete example of something that has both, one can check e.g. `libcusparse`:
```
[casparl@tcn1 ~]$ cuobjdump /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/CUDA/12.1.1/lib64/libcusparse.so | grep -A 5 ptx | tail -n 12
================
arch = sm_80
code version = [8,1]
host = linux
compile_size = 64bit
--
Fatbin ptx code:
================
arch = sm_90
code version = [8,1]
host = linux
compile_size = 64bit
[casparl@tcn1 ~]$ cuobjdump /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/CUDA/12.1.1/lib64/libcusparse.so | grep -A 5 elf | tail -n 12
================
arch = sm_80
code version = [1,7]
host = linux
compile_size = 64bit
--
Fatbin elf code:
================
arch = sm_90
code version = [1,7]
host = linux
compile_size = 64bit
```

2025-02-19 21:00 UTC, casparvl commented on easybuild/framework/easyblock.py
> +        if get_software_root('CUDA'):
Wait... actually, I don't think you're right. Because I just did this with `EESSI-extend`, and it _did_ run the CUDA sanity check...? I'm not sure why, I would have _expected_ the problem you mentioned. So... why didn't it appear?

2025-02-20 22:45 UTC, casparvl commented
Ignore list seems to work. Adding
```
cuda_sanity_ignore_files = ['bin/watershedSegmentationNPP', 'bin/simpleTemplates_nvrtc']
```
to the EasyConfig for CUDA-Samples results in
```
== 2025-02-20 23:43:16,229 easyblock.py:3350 DEBUG Sanity checking for CUDA device code in /home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1
.1/bin/simpleTemplates_nvrtc
== 2025-02-20 23:43:16,229 run.py:489 INFO Path to bash that will be used to run shell commands: /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/bin/bash
== 2025-02-20 23:43:16,229 run.py:500 INFO Running shell command 'file /home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/simpleTemplat
es_nvrtc' in /tmp/casparl/easybuild/build/CUDASamples/12.1/GCC-12.3.0-CUDA-12.1.1/cuda-samples-12.1
== 2025-02-20 23:43:16,235 run.py:598 INFO Output of 'file ...' shell command (stdout + stderr):
/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/simpleTemplates_nvrtc: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamica
lly linked, interpreter /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, not stripped

== 2025-02-20 23:43:16,235 run.py:601 INFO Shell command completed successfully (see output above): file /home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12
.3.0-CUDA-12.1.1/bin/simpleTemplates_nvrtc
== 2025-02-20 23:43:16,235 run.py:489 INFO Path to bash that will be used to run shell commands: /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/bin/bash
== 2025-02-20 23:43:16,235 run.py:500 INFO Running shell command 'cuobjdump /home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/simpleTe
mplates_nvrtc' in /tmp/casparl/easybuild/build/CUDASamples/12.1/GCC-12.3.0-CUDA-12.1.1/cuda-samples-12.1
== 2025-02-20 23:43:16,240 run.py:598 INFO Output of 'cuobjdump ...' shell command (stdout + stderr):

Fatbin elf code:
================
arch = sm_52
code version = [1,7]
host = linux
compile_size = 64bit

== 2025-02-20 23:43:16,240 run.py:601 INFO Shell command completed successfully (see output above): cuobjdump /home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-G
CC-12.3.0-CUDA-12.1.1/bin/simpleTemplates_nvrtc
== 2025-02-20 23:43:16,241 easyblock.py:3376 WARNING Mismatch between cuda_compute_capabilities and device code in /home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/1
2.1-GCC-12.3.0-CUDA-12.1.1/bin/simpleTemplates_nvrtc. Surplus compute capabilities: 5.2. Missing compute capabilities: 8.0. This failure will be ignored as /home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/simpleTemplates_nvrtc is listed in 'ignore_cuda_sanity_failures'.
== 2025-02-20 23:43:16,241 easyblock.py:3393 WARNING Configured highest compute capability was '8.0', but no PTX code for this compute capability was found in '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/simpleTemplates_nvrtc' PTX architectures supported in that file: []
```
and note that this binary does _not_ get listed in the failure message. So that's the intended behavior: the warning is still printed, but it doesn't result in an error.

2025-02-21 16:21 UTC, casparvl commented
Just to test: putting all of these files in the ignore list, the installation of CUDA-Samples now passes.
```
cuda_sanity_ignore_files = [
    'bin/binomialOptions_nvrtc',
    'bin/jitLto',
    'bin/inlinePTX_nvrtc',
    'bin/conjugateGradientCudaGraphs',
    'bin/simpleVoteIntrinsics_nvrtc',
    'bin/MersenneTwisterGP11213',
    'bin/nvJPEG_encoder',
    'bin/vectorAdd_nvrtc',
    'bin/clock_nvrtc',
    'bin/nvJPEG',
    'bin/BlackScholes_nvrtc',
    'bin/simpleAtomicIntrinsics_nvrtc',
    'bin/batchedLabelMarkersAndLabelCompressionNPP',
    'bin/conjugateGradient',
    'bin/simpleAssert_nvrtc',
    'bin/matrixMul_nvrtc',
    'bin/cuSolverDn_LinearSolver',
    'bin/quasirandomGenerator_nvrtc',
    'bin/watershedSegmentationNPP',
    'bin/simpleTemplates_nvrtc'
]
```

This provides a nice starting point for further tests, I can easily just remove one from the exclude list, and check that I get the expected result.

2025-02-21 18:09 UTC, casparvl commented
So... the whole thing with checking PTX codes makes me rethink what EasyBuild _should_ do when a certain `--cude-device-compute-capabilities` is set. Currently, this is ill-defined at best. Our official docs say:

> List of CUDA compute capabilities to use when building GPU software;
                        values should be specified as digits separated by a dot, for example:
                        3.5,5.0,7.2 (type comma-separated list)

But what does that mean? What do we expect the nvcc compiler to do here? Say we were to compile a simple hello world, and I would do `--cuda-compute-capabilies=8.0,9.0`, what would I expect my `nvcc` invocation to look like?

```
nvcc hello.cu --gpu-architecture=compute_80 --gpu-code=sm_80,sm_90 -o hello
```
i.e. would it only build device code for 80/90, and not include PTX? And build both through the lowest common virtual architecture? Or should it do

```
nvcc hello.cu --gpu-architecture=compute_80 --gpu-code=sm_80,sm_90,compute_80 -o hello
```
i.e. also include the PTX code for the `--gpu-architecture` we specified? Or do we expect it to use the generalized option `--generate-code` so that it does
```
nvcc hello.cu  --generate-code=arch=compute_80,code=sm_80 --generate-code=arch=compute_90,code=sm_90 -o hello
```
i.e. the stage one compilation is executed once for each CUDA compute capability, so that the generated `sm_90` code can actually use the features from the `compute_90` architecture? Or do we expect it to do
```
nvcc hello.cu  --generate-code=arch=compute_80,code=sm_80 --generate-code=arch=compute_90,code=sm_90 --generate-code=arch=compute_90,code=compute_90 -o hello
```
so that it actually includes not only the device codes for CC80 and CC90, but _also_ the PTX code for CC90 (for forwards compatibility)?

Honestly, from a performance perspective, I think it would be _best_ if EasyBuild would indeed use the generalized arguments, so that the `sm_90` code would use the full capabilities of the `compute_90` virtual architecture. Since EasyBuild focusses on performance, I think this makes sense. The only price you pay is longer compilation time, since you also have to build that `compute_90` virtual architecture PTX code. Whether to include the PTX code is a different question. As proposed above, I think this should be a separate option in EasyBuild, so that one can decide in the EB config whether to ship PTX code, and which version(s).

I.e. my proposal would be that if EasyBuild is configured with `--cuda-compute-capabilities=7.0,8.0,9.0` and `--cuda-virtual-architectures=7.0,9.0` that this would trigger:
```
nvcc hello.cu  --generate-code=arch=compute_70,code=sm_70 --generate-code=arch=compute_80,code=sm_80 --generate-code=arch=compute_90,code=sm_90 --generate-code=arch=compute_70,code=compute_70 --generate-code=arch=compute_90,code=compute_90 -o hello
```
Note that it may not always be possible to convince all build systems to actually do this - e.g. some codes might really only compile for a single cuda-compute-capability, or the build system doesn't make this distinction between real and virtual architectures to build for. _Eventually_ the most robust and generic way to get this done might just be to implement `nvcc` compiler wrappers that inject these `--generate-code` arguments.

I'm creating a CUDA hello world EasyConfig that we can use to serve as an easy example of 1) how we think `--cuda-compute-capabilities` and `--cuda-virtual-architectures` should work in EasyBuild and 2) have an EasyConfig with which we can easily test these things, including the sanity check.

I'm not sure what the best way forward is. If I include everything in this PR, it may be a bit heavy - although honestly at the framwork level it's just about defining the _options_, the real implementation would have to be done in EasyBlocks and EasyConfigs that use this information...

My plan is to include the options in this PR, and make an accompanying PR for my CUDA hello world that uses these options in the way described above. The rest is then up to anyone updating or creating new EasyBlocks/EasyConfigs that somehow use information on the CUDA compute capability.

2025-02-21 18:50 UTC, casparvl commented
Ok, change of plans. After thinking it over, this would be a massive scope creep that would delay the sanity check part that we primarily care about in this PR. Instead, in this PR, I'll focus on just that: a sanity check for the CUDA device codes. We can assume that everyone using EasyBuild expect _this_ to be the meaning of the `--cuda-compute-capabilities`, i.e. they expect if they specify `8.0,9.0` that the resulting binaries contain device code for `8.0` and `9.0`. Which virtual architecture was used to get there, or what PTX codes are shipped as part of the binary are not relevant to that expectation, and can be considered further optimizations that we can do in a separate PR.

I _will_ retain the code that prints a warning for the PTX code not matching the highest architecture. Or maybe demote it to an info message. In any case, it's convenient for future reference if EasyBuild extracts this information.

I will _not_ implement a strict option for the PTX code sanity check in this PR. It does not make sense to be sanity checking for behavior that we haven't clearly defined, i.e. there is no clear definition of what PTX code is _expected_ to be included when someone sets `--cuda-compute-capabilities`.

2025-02-21 19:36 UTC, casparvl commented
Everything _not_ sanity-check related is now described in [this issue](https://github.com/easybuilders/easybuild-framework/issues/4770), which can be used to create one or more follow-up PRs.

2025-02-21 20:50 UTC, casparvl commented
Tested by adding

```
cuda_sanity_ignore_files = [
    'bin/binomialOptions_nvrtc',
    'bin/jitLto',
    'bin/inlinePTX_nvrtc',
    'bin/conjugateGradientCudaGraphs',
    'bin/simpleVoteIntrinsics_nvrtc',
    'bin/MersenneTwisterGP11213',
    'bin/nvJPEG_encoder',
    'bin/vectorAdd_nvrtc',
    'bin/clock_nvrtc',
    'bin/nvJPEG',
    'bin/BlackScholes_nvrtc',
    'bin/simpleAtomicIntrinsics_nvrtc',
    'bin/batchedLabelMarkersAndLabelCompressionNPP',
    # 'bin/conjugateGradient',
    'bin/simpleAssert_nvrtc',
    'bin/matrixMul_nvrtc',
    'bin/cuSolverDn_LinearSolver',
    'bin/quasirandomGenerator_nvrtc',
    'bin/watershedSegmentationNPP',
    'bin/simpleTemplates_nvrtc'
]
```
To `CUDA-Samples-12.1-GCC-12.3.0-CUDA-12.1.1.eb`. Then, with:
```
eb CUDA-Samples-12.1-GCC-12.3.0-CUDA-12.1.1.eb --rebuild
```
my build succeeds whereas with
```
```
eb CUDA-Samples-12.1-GCC-12.3.0-CUDA-12.1.1.eb --rebuild --strict-cuda-sanity-check
```
It fails with:
```
== 2025-02-21 21:41:21,349 build_log.py:226 ERROR EasyBuild encountered an error (at easybuild/easybuild-framework/easybuild/tools/build_log.py:166 in caller_info): Sanity check failed: Mismatch between cuda_compute_capabilities and device code in /home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/conjugateGradient. Surplus compute capabilities: 5.0, 5.2, 6.0, 6.1, 7.0, 7.5, 8.6, 8.9, 9.0.  (at easybuild/easybuild-framework/easybuild/framework/easyblock.py:4010 in _sanity_check_step)
```
as intended.

Only thing left to do for this PR is tests. Not my strong suit to be honest, but let's see. I guess the tricky thing here is that a true test requires a _real_ CUDA binary, and I'm not sure that's even feasible... To build one, I'd need a CUDA module in the test environment - I'm not sure if we have that. I could try to find a CUDA binary that we could just install (maybe just include a hello-world type of CUDA binary) and test with that... Maybe that's the most feasible option. But I have no clue if we can reasonable include binaries in the repo under the test directory. I have an 800KB hello world binary, that shouldn't be _too_ crazy I guess.

2025-02-21 21:09 UTC, ocaisa commented
What you can do is create a mock `cuobjdump` script that parrots output, you're only checking that EBcan run the code and paste the output.

2025-02-21 21:34 UTC, casparvl commented
Damn your good, it took me 25 more minutes of looking at other examples to figure out that even if I could ingest a binary, I'd lack the `cuobjdump` executable. Might indeed as well fake `cuobjdump` output on a `toy` build example.

2025-02-22 10:31 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +        if get_software_root('CUDA'):
I wonder what happens in the `--module-only` case, when the sanity check step is being run without building first? Perhaps this really is expected behaviour?

2025-03-04 19:39 UTC, casparvl commented
Note to self: to run the new test locally, do `python -m test.framework.toy_build cuda`.

2025-03-12 14:30 UTC, ocaisa requested changes

2025-03-12 14:30 UTC, ocaisa commented on easybuild/framework/easyconfig/default.py
> +    'cuda_sanity_ignore_files': [[], "List of files (relative to the installation prefix) for which failurs in "
```suggestion
    'cuda_sanity_ignore_files': [[], "List of files (relative to the installation prefix) for which failures in "
```

2025-03-12 16:53 UTC, casparvl commented on easybuild/framework/easyblock.py
> +                for path in [os.path.join(dirpath, x) for x in os.listdir(dirpath)]:
I'll double check, but I _think_ this was done to keep things consistent with... how things were done elsewhere (RPATH sanity check?). I'll need to check. We don't _technically_ need to do the same, but it might get confusing if we don't (I think some of the configuration things we use, like `bin_lib_subdirs` _do_ match between the two. So it might be extra confusing if some of this then does subdirs too, and others don't - would a user have to define subdirs on `bin_lib_subdirs` or not?).

Anyway, I'll dig into it a bit and check.

2025-03-18 09:34 UTC, casparvl commented
Just had a chat with Alan. Writing down some conclusions here:

- We want an option (e.g. `--accept-ptx-for-cc-support`) to pass the sanity check if the right PTX code is available. I.e. if `--cuda-compute-capabilities=8.0`, and we have a binary without device code but **with** e.g. PTX for 7.0, this could be acceptable, because this binary _will run_ on an 8.0 device (it might just not be optimal).
- We will _not_ create a separate option for EB to request specific PTX codes at this time, as we consider that over-engineering. The use cases exist (e.g. compile device code for 5.0, and 8.0, and then device code for 6.0 and 8.0, so that both 6.0 and 7.0 are support through the 6.0 PTX code, as well as future archs through the 8.0 PTX code), but are very specific - and one might wonder "why not just make a 'fatter' binary with 5.0, 6.0, 7.0, 8.0 device code, and 8.0 PTX code".
- We will document what the expected behavior of EasyBuild is if you set a `--cuda-compute-capability`. And, we will define that that behavior _should_ be: create device code for every item in the `--cuda-compute-capability` list _and_ create PTX code for the highest architecture in that list.
- We will update the current sanity check so that it can also produce failures if PTX code is missing for the highest CC (currently, that's a warning). We will introduce an option to push that down to a warning, as not everyone might strictly require forward compatibility.

2025-03-19 10:50 UTC, boegel commented
@jfgrimm I changed to target branch in this PR from `5.0.x` to `develop`, you should synchronize your PR branch with current `develop` branch (which has received a massive update after the release of EasyBuild v5.0.0, see #4825)

2025-04-03 14:04 UTC, casparvl commented on easybuild/framework/easyblock.py
> +                for path in [os.path.join(dirpath, x) for x in os.listdir(dirpath)]:
Yes, I kept things in sync with the `RPATH` check.

```
       for dirpath in [os.path.join(self.installdir, d) for d in rpath_dirs]:
            if os.path.exists(dirpath):
                self.log.debug(f"Sanity checking RPATH for files in {dirpath}")

                for path in [os.path.join(dirpath, x) for x in os.listdir(dirpath)]:
                    self.log.debug(f"Sanity checking RPATH for {path}")
```

I propose to keep it for now. We can change it in a follow-up PR, but then we'd probably want to do it for both the CUDA and RPATH sanity checks.

2025-04-03 14:04 UTC, casparvl commented on easybuild/framework/easyblock.py
> +                self.log.debug(f"Sanity checking files for CUDA device code in {dirpath}")
Changed

2025-04-03 14:05 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            cuda_dirs = self.cfg['bin_lib_subdirs'] or self.bin_lib_subdirs()
Sounds like a reasonable default, yes. But indeed, outside of this PRs scope, so I'll leave it for now.

2025-04-03 14:07 UTC, casparvl commented on easybuild/framework/easyconfig/default.py
> +    'cuda_sanity_ignore_files': [[], "List of files (relative to the installation prefix) for which failurs in "
Fixed

2025-04-03 14:11 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            cuda_fails = self.sanity_check_cuda()
> How do I pass in cuda_dirs? I would have expected that to be an easyconfig parameter

How do you pass in `rpath_dirs` for the `sanity_check_rpath`? :D I think it is there so that you can pass it in when writing a custom EasyBlock, no? E.g. this https://github.com/easybuilders/easybuild-easyblocks/blob/59b4ecbd65b51b5c31f3830f74233c60a3c28a64/easybuild/easyblocks/generic/gopackage.py#L156 _could_ have modified the `rpath_dirs` argument (it doesn't, but it could have). Same for this cuda sanity check, it just provides an easy interface for inheriting EasyBlocks to modify it.

2025-04-03 14:27 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            cuda_fails = self.sanity_check_cuda()
> It's probably also worth making sure cuobjdump is actually available/working before proceeding

Done

2025-04-03 14:29 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            return fails
Fixed

2025-04-03 14:33 UTC, casparvl commented on easybuild/tools/systemtools.py
> +        return None
Fixed

2025-04-03 14:35 UTC, casparvl commented on easybuild/tools/systemtools.py
> +        return res.output
Hmmm... I think you are actually too primed by the pattern. This is _not_ an early return, it's an if-else, and both conditions end in a return. But just to be sure: I'll collect the return status and make it a _single_ return. Honestly, I'm not a big fan of that pattern personally, but I don't care enough to dispute it either :)

2025-04-03 14:35 UTC, casparvl commented on easybuild/tools/systemtools.py
> +        return None
Hmmm... I think you are actually too primed by the pattern. This is _not_ an early return, it's an if-else, and both conditions end in a return. But just to be sure: I'll collect the return status and make it a _single_ return. Honestly, I'm not a big fan of that pattern personally, but I don't care enough to dispute it either :)

2025-04-03 14:40 UTC, casparvl commented on easybuild/tools/systemtools.py
> +        return None
Changed (though honestly, I find this much less readable then the early return :|)

2025-04-08 16:36 UTC, casparvl commented
We're getting closer... functionality is as I specified in earlier comments in this PR. TODO: update the unit tests, since we now have more flags and features that need to be checked.

Currently, I get the following summary reports:
```
$ eb CUDA-Samples-12.1-GCC-12.3.0-CUDA-12.1.1.eb --rebuild --disable-strict-cuda-sanity-check --accept-missing-cuda-ptx --accept-ptx-as-cc-support
...
== 2025-04-08 17:53:10,075 easyblock.py:3596 INFO CUDA sanity check summary report:
Number of CUDA files checked: 142
Number of files missing one or more CUDA Compute Capabilities: 15 (ignored: 0, fails: 15)
Number of files missing one or more CUDA Compute Capabilities, but has suitable PTX code that can be JIT compiled for the requested CUDA Compute Capabilities: 0
Number of files with device code for more CUDA Compute Capabilities than requested: 20 (not running with --strict-cuda-sanity-check, so not considered failures)
Number of files missing PTX code for the highest configured CUDA Compute Capability: 47 (running with --accept-missing-cuda-ptx so not considered failures)

== 2025-04-08 17:53:10,075 easyblock.py:3611 DEBUG Detailed CUDA sanity check summary report:
Files missing one or more CUDA compute capabilities: ['/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/jitLto', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/inlinePTX_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/binomialOptions_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/simpleVoteIntrinsics_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/nvJPEG_encoder', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/vectorAdd_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/clock_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/nvJPEG', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/BlackScholes_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/simpleAtomicIntrinsics_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/simpleAssert_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/matrixMul_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/cuSolverDn_LinearSolver', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/quasirandomGenerator_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/simpleTemplates_nvrtc']
These failures are ignored for: [])
Files missing one or more CUDA Compute Capabilities, but has suitable PTX code that can be JIT compiled for the requested CUDA Compute Capabilities: []
Files with device code for more CUDA Compute Capabilities than requested: ['/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/jitLto', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/inlinePTX_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/conjugateGradientCudaGraphs', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/binomialOptions_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/simpleVoteIntrinsics_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/MersenneTwisterGP11213', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/nvJPEG_encoder', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/vectorAdd_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/clock_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/nvJPEG', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/BlackScholes_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/simpleAtomicIntrinsics_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/batchedLabelMarkersAndLabelCompressionNPP', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/conjugateGradient', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/simpleAssert_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/matrixMul_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/cuSolverDn_LinearSolver', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/quasirandomGenerator_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/watershedSegmentationNPP', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/simpleTemplates_nvrtc']
These failures are ignored for: [])
Files missing PTX code for the highest configured CUDA Compute Capability: ['/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/vectorAddMMAP', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/jitLto', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/inlinePTX_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/deviceQueryDrv', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/cdpQuadtree', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/batchCUBLAS', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/cdpBezierTessellation', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/cuSolverSp_LowlevelQR', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin/binomialOptions_nvrtc', '/home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2 [...]

2025-04-10 08:42 UTC, ocaisa requested changes

2025-04-10 08:42 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +                                            fail_msg += ignore_msg
```suggestion
                                            if not ignore_failures:
                                                fail_msg += ignore_msg
```

2025-04-10 08:42 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +                                    fail_msg += ignore_msg
```suggestion
                                    if not ignore_failures:
                                        fail_msg += ignore_msg
```

2025-04-10 08:42 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +                summary_msg += "Number of files missing one or more CUDA Compute Capabilities, but has suitable "
```suggestion
                summary_msg += "Number of files missing one or more CUDA Compute Capabilities, but having suitable "
```

2025-04-10 08:42 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +            if strict_cc_check:
```suggestion
            if strict_cc_check and not ignore_failures:
```

2025-04-10 08:42 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +            if accept_missing_ptx:
```suggestion
            if accept_missing_ptx or ignore_failures:
```

2025-04-10 08:42 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +            if num_files_missing_cc > 0 and not accept_ptx_as_cc:
For tis and others below we should consider what to say when failures are being ignored by default (which is likely to be the default for EasyBuild).

2025-04-10 08:42 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +            self.log.info(summary_msg)
Perhaps if `ignore_failures` is set we actually print the `summary_msg` as a warning?

2025-04-10 08:42 UTC, ocaisa commented on easybuild/tools/options.py
> +                                          "for example: 3.5,5.0,7.2. EasyBuild will compile a fat binaries with "
```suggestion
                                          "for example: 3.5,5.0,7.2. EasyBuild will (where possible) compile fat binaries with "
```

2025-04-10 08:42 UTC, ocaisa commented on easybuild/tools/systemtools.py
> +                msg = "Dumping CUDA binary file information for '%s' via '%s' failed! Output: '%s'"
Why is this not an error?

2025-04-10 08:42 UTC, ocaisa commented on easybuild/tools/systemtools.py
> +            _log.warning(fail_msg)
This is basically the same code as above, can we just loop over a list of tuples for regex/fail_msg?

My AI friend said
```
def extract_architecture(cuda_raw, code_regex, section_regex, section_type, path):
    matches = re.findall(code_regex, cuda_raw)
    if matches:
        # Convert match tuples into a unique list of CUDA compute capabilities
        # e.g., [('8', '6'), ('8', '6'), ('9', '0')] -> ['8.6', '9.0']
        return sorted(['.'.join(m) for m in set(matches)])
    else:
        section_matches = re.findall(section_regex, cuda_raw)
        if section_matches:
            fail_msg = f"Found Fatbin {section_type} code section(s) in cuobjdump output for {path}, but failed to extract CUDA architecture"
        else:
            fail_msg = f"Failed to find Fatbin {section_type} code section(s) in cuobjdump output for {path}, are you sure this is a CUDA binary?"
        _log.warning(fail_msg)
        return None

# Extract device code architectures
device_code_matches = extract_architecture(cuda_raw, device_code_regex, 'Fatbin elf', 'elf', path)

# Extract ptx code architectures
ptx_code_matches = extract_architecture(cuda_raw, ptx_code_regex, 'Fatbin ptx', 'ptx', path)

```

2025-04-10 09:06 UTC, boegel requested changes

2025-04-10 09:06 UTC, boegel commented on easybuild/tools/systemtools.py
> +        cuda_cmd = f"cuobjdump {path}"
What if `cuobjdump` is not around? At least emit a clear log message.

Maybe also change return type of this function:

* `(None, f"{path} is not an executable, object, library")`
* `(None, f"{path} does not contain CUDA device code")`
* `(False, "cuobjdump command not found")`
* `(False, f"cuobjdump failed: {res.output}")`
* `(True, res.output)`

2025-04-10 10:02 UTC, boegel requested changes

2025-04-10 10:02 UTC, boegel commented on easybuild/framework/easyblock.py
> +
add log info (or warning) message here to show how many failing files were found:
```suggestion
self.log.info(f"{len(files_surplus_cc) files found with additional device code architecture: {files_surplus_cc}")
```

maybe only paths relative to install dir, something like:

```python
[os.path.relpath(x, self.installdir) for x in files_surplus_cc]

2025-04-10 10:26 UTC, jfgrimm commented on easybuild/tools/systemtools.py
> +        cuda_cmd = f"cuobjdump {path}"
`cuobjdump` is part of the CUDA toolkit, so it really should be found; it should be an error if not

2025-04-10 11:53 UTC, casparvl commented on easybuild/framework/easyblock.py
> +        fails = []
`sanity_check_rpath` also uses ` fails`, but... sure, `fail_msgs` it is :D

2025-04-10 12:25 UTC, ocaisa commented on easybuild/tools/systemtools.py
> +        cuda_cmd = f"cuobjdump {path}"
The case I am worried about is EESSI as in there we demote `CUDA` to a build dependency (and rely on rpath linking to access the runtime). Right now, it seems the build dependency is still loaded during the sanity check step so I think we are covered...but there is a danger that this behaviour will change.

2025-04-10 12:30 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            num_files_missing_cc_but_has_ptx = 0
Done, and replaced all uses of `num_X` with `len(...)` of the corresponding `files_X`

2025-04-10 12:31 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            self.log.info("Skipping CUDA sanity check, as no CUDA compute capabilities where configured")
Oh dear, such a 'Dutch' mistake this one... :D

2025-04-10 12:36 UTC, casparvl commented on easybuild/tools/systemtools.py
> +        cuda_cmd = f"cuobjdump {path}"
I think it doesn't hurt to check for the presence of `cuobjdump`. The check for the CUDA toolkit happens in the sanity check, but in the future, _someone else_ might call this function from a different place and have no such check for CUDA toolkit in place.

2025-04-10 12:37 UTC, jfgrimm commented on easybuild/tools/systemtools.py
> +        cuda_cmd = f"cuobjdump {path}"
I guess you could work around it by adding an EB configuration option to point to a particular `cuobjdump` to use for the sanity check? e.g. `--cuda-sanity-check-cuobjdump=/path/to/some/cuobjdump`. We don't need the CUDA toolkit version that provides that `cuobjdump` to match the version used in the installation

2025-04-10 12:39 UTC, jfgrimm commented on easybuild/framework/easyblock.py
> +        if get_software_root('CUDA'):
matching the `rpath` sanity check behaviour makes sense to me

2025-04-10 12:53 UTC, casparvl commented on easybuild/tools/options.py
> +                                            None, 'store_true', True),
Renamed as suggested, with one exception:
```
cuda-sanity-check-accept-ptx-as-devcode
```
because we later decided that it should really be devcode and not cc :)

2025-04-10 13:08 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            self.log.info("Skipping CUDA sanity check, as no CUDA compute capabilities where configured")
Done

2025-04-10 13:10 UTC, casparvl commented on easybuild/framework/easyblock.py
> +                            if additional_ccs or missing_ccs:
Done

2025-04-10 13:11 UTC, casparvl commented on easybuild/framework/easyblock.py
> +                                    fail_msg += "Surplus compute capabilities: %s. " % surplus_cc_str
Changed

2025-04-10 13:12 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            files_missing_cc = []
Changed

2025-04-10 13:15 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            summary_msg += f"Number of files missing one or more CUDA Compute Capabilities: {num_files_missing_cc} "
Changed all of those.

2025-04-10 13:16 UTC, casparvl commented on easybuild/framework/easyblock.py
> +
I'll actually do this when _appending_ the path, so that the long path never makes it into the list. No point, really.

2025-04-10 13:27 UTC, casparvl commented on easybuild/framework/easyblock.py
> +
Wait, no, you're suggested location actually doesn't make sense: this is _inside_ the loop. That would print an increasingly growing list.

We can do two things:
- print the _individual_ path to `self.log.info` right away (i.e. at the location where we `append` it to some list)
- print the lists right after the for-loop

Now that we've reduce the length of the paths, I'm in favor of doing this after the for loop (but then before the 'summary in numbers', so that that's the last thing you get from the sanity check - that way it stands out).

2025-04-10 13:34 UTC, casparvl commented on easybuild/framework/easyblock.py
> +
Ok, I'm now printing all, but after the for-loop.

2025-04-10 14:42 UTC, casparvl commented on easybuild/tools/systemtools.py
> +        cuda_cmd = f"cuobjdump {path}"
First, let's see if it's actually an issue, as with `EESSI-extend`, I haven't seen it (even though, like Alan, I did expect it)... We can easily fix that in a subsequent PR

2025-04-10 14:51 UTC, casparvl commented on easybuild/framework/easyblock.py
> +                                        if all(comparisons):
Done

2025-04-10 14:58 UTC, casparvl commented on easybuild/tools/systemtools.py
> +def get_cuda_device_code_architectures(path):
Done

2025-04-10 15:03 UTC, casparvl commented on easybuild/tools/systemtools.py
> +            device_code_matches = sorted(['.'.join(m) for m in set(device_code_matches)])
Fixed

2025-04-10 15:03 UTC, casparvl commented on easybuild/tools/systemtools.py
> +            ptx_code_matches = sorted(['.'.join(m) for m in set(ptx_code_matches)])
Fixed

2025-04-10 15:13 UTC, casparvl commented on easybuild/tools/systemtools.py
> +                msg = "Dumping CUDA binary file information for '%s' via '%s' failed! Output: '%s'"
Fixed

2025-04-10 15:13 UTC, casparvl commented on easybuild/tools/options.py
> +                                          "for example: 3.5,5.0,7.2. EasyBuild will compile a fat binaries with "
Changed.

2025-04-10 15:15 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            self.log.info(summary_msg)
I think that's actually a great idea (though note that we already print warning for the individual things that would have been a failure).

2025-04-14 12:38 UTC, casparvl commented on easybuild/framework/easyblock.py
> +                                            fail_msg += ignore_msg
See previous

2025-04-14 12:38 UTC, casparvl commented on easybuild/framework/easyblock.py
> +                                    fail_msg += ignore_msg
See previous

2025-04-14 15:14 UTC, casparvl commented on easybuild/framework/easyblock.py
> +                                                fail_msg += ignore_msg
Fixed, see above.

2025-04-14 15:15 UTC, casparvl commented on easybuild/framework/easyblock.py
> +                summary_msg += "Number of files missing one or more CUDA Compute Capabilities, but has suitable "
Fixed.

2025-04-14 15:17 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            if strict_cc_check:
I would still print this (like all the other ones): it will simply report that there _are_ files with additional CCs, but that all of those are ignored.

2025-04-14 15:20 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            if strict_cc_check:
Actually: I'll make an extra `elif` with a more specific message that it's not considered a failure because someone is running with `--disable-cuda-sanity-check-error-on-fail`.

2025-04-14 15:25 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            if strict_cc_check:
Fixed, now give a specific message for `if ignore_failures: ... elif strict_cc_check: ... else: ...`

2025-04-14 15:25 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            if accept_missing_ptx:
Fixed, now give a specific message for `if ignore_failures: ... elif accept_missing_ptx: ... else: ...`

2025-04-14 15:33 UTC, casparvl commented
Ok, getting closer... Implemented nearly all comments. Only thing left to do:
- Implement unit tests for `get_cuda_architectures` and `get_cuda_object_dump_raw`
- Re-evaluate existing unit tests that test the CUDA sanity check.
    - Some where broken in CI (because of option renaming?)
    - We have new options, so should make sure we test _all_ options
    - We should make sure we test all cases (missing device code, missing PTX, multiple device codes requested in `--cuda-compute-capabilities`, etc)

2025-04-16 11:35 UTC, casparvl commented on test/framework/toy_build.py
> +        ])
I revised most of the tests. Also made sure to add one for 'no device code' this time.

2025-04-16 11:36 UTC, jfgrimm commented on test/framework/toy_build.py
> +        expected_summary += r"\(not running with --cuda-sanity-check-fail-on-error, so not considered failures\)$\n"
@casparvl have you considered configuring your editor of choice to automatically strip trailing whitespace for *.eb *.py files? :P

2025-04-16 11:37 UTC, jfgrimm commented on test/framework/toy_build.py
> +        expected_summary += r"\(not running with --cuda-sanity-check-fail-on-error, so not considered failures\)$\n"
if you're a vim aficionado, `autocmd BufWritePre *.py,*.eb :%s/\s\+$//e`

2025-04-16 13:53 UTC, casparvl commented on test/framework/toy_build.py
> +        expected_summary += r"\(not running with --cuda-sanity-check-fail-on-error, so not considered failures\)$\n"
Btw, thanks for that command, very useful :)

2025-04-22 12:26 UTC, casparvl commented on easybuild/tools/systemtools.py
> +def get_cuda_object_dump_raw(path):
done

2025-04-24 13:15 UTC, jfgrimm commented on easybuild/framework/easyblock.py
> +                for path in [os.path.join(dirpath, x) for x in os.listdir(dirpath)]:
for the rpath sanity checks, I've got a PR open to avoid following symlinks to directories outside of the install dir https://github.com/easybuilders/easybuild-framework/pull/4854/files
we probably want something similar here

2025-05-08 13:57 UTC, ocaisa requested changes
Interim review with some trivial things, taking it for a test drive and then a proper full readthrough

2025-05-09 07:32 UTC, ocaisa commented
In the summary report of the log file (when using current default settings) I see:
```
== 2025-05-09 09:20:09,189 easyblock.py:3675 WARNING CUDA sanity check summary report:
Number of CUDA files checked: 142
Number of files missing one or more CUDA Compute Capabilities: 15 (not running with --cuda-sanity-check-fail-on-error, so not considered failures)
Number of files with device code for more CUDA Compute Capabilities than requested: 20 (not running with --cuda-sanity-check-fail-on-error, so not considered failures)
Number of files missing PTX code for the highest configured CUDA Compute Capability: 47 (not running with --cuda-sanity-check-fail-on-error, so not considered failures)

You may consider rerunning with --cuda-sanity-check-accept-ptx-as-devcode to accept binaries that don't contain the device code for your requested CUDA Compute Capabilities, but that do have PTX code that can be compiled for your requested CUDA Compute Capabilities. Note that this may increase startup delay due to JIT compilation and may also lead to suboptimal runtime performance, as the PTX code may not exploit all features specific to your hardware architecture.

You may consider running with --cuda-sanity-check-accept-missing-ptx to accept binaries that don't contain PTX code for the highest CUDA Compute Capability you requested. This breaks forwards compatibility for newer CUDA Compute Capabilities (i.e. your compiled binaries will not run on cards with higher CUDA Compute Capabilities than what you requested in --cuda-compute-capabilities), but that may be acceptable to you.
```
This is a little painful to find and will be easily missed. I think this summary should be printed to the screen. The second and third paragraphs should only be seen if they are relevant:

- if the user is on default settings, you should explain the option to enforce the check (`--cuda-sanity-check-fail-on-error`) in a separate paragraph (and I think we want a section in the docs on this to point to, we should create something simple now so we have a URL to point to, and we can improve it later)
- if they have set any of the other options set, you should assume they know what they are doing and only print the options that might help them workaround a specific problem

2025-05-09 07:42 UTC, ocaisa commented
You should also mention that detailed information is available in the log and what they should search for to find it (at and before `/CUDA sanity check`)

2025-05-09 13:55 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +            self.log.warning(summary_msg)
```suggestion
            self.log.warning(summary_msg)
            print_warning(summary_msg)
```

2025-05-09 14:03 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +        if get_software_root('CUDA'):
This concerns me a little bit, as it may in the future lead to a funny situation. Right now it seems that even though CUDA is demoted to a build dep for EESSI it is loaded during the sanity check. _If_ that were to change this sanity check would never get called. Perhaps better to check if CUDA is in full list of dependencies?

2025-05-09 14:09 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +        if get_software_root('CUDA'):
I think it might be 
```
if 'CUDA' in [dep['name'] for dep in self.dependencies()]
```

2025-05-12 10:28 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +        files_missing_devcode_but_has_ptx = []
When it comes to printing these later, can we format them so they are printed in a more easy-to-read way in the logs later? Something like
```
files_missing_ptx_str = "\n" + "\n".join(f"  {f}" for f in files_missing_ptx)
```

2025-05-12 11:46 UTC, casparvl commented on easybuild/framework/easyblock.py
> +        files_missing_devcode_but_has_ptx = []
You mean: in addition to having the files on a new line after the 
"XXX files missing PTX code for the highest configured CUDA Compute Capability" that we don't print a single _line_ listing the files, but _each_ file on a single line? Sure, that's possible. But note that it might be a _lot_ of files, and thus a lot of lines! But you may be right that a single _very_ long line is probably still worse ;-)

2025-05-12 11:50 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +        files_missing_devcode_but_has_ptx = []
It might just be quicker than adding all those `\n` later as per my original suggestion, preformatting the lists should make that a bit easier. Could be done via a function so we can easily tweak this later:
```
def format_file_list_as_string(files_list):
    return "\n" + "\n".join(f"  {f}" for f in files_list)
``

2025-05-12 14:35 UTC, casparvl commented on easybuild/framework/easyblock.py
> +                                fail_msg += ignore_msg
I managed to reproduce your failure running 
```
eb CUDA-Samples-12.1-GCC-12.3.0-CUDA-12.1.1.eb --rebuild
```
I was surprised this wasn't caught by the unit tests, but I see why: I _do_ run with default options in test case 1, but in that case there _is_ PTX code present for the requested CUDA arch, so it never hits this code path. I'll add a test case where we use default options and there is no PTX code.

2025-05-12 15:43 UTC, casparvl commented on easybuild/framework/easyblock.py
> +        if get_software_root('CUDA'):
Hm... But the fact that it's on the dependency list is not enough: we _need_ it to be loaded if we are to use `cuobjdump`.

I was going to propose to leave a breadcrumb here in the form of a comment that we _may_ need to change this if framework ever gets changed so that the build deps are no longer loaded at sanity check stage (which I agree should probably actually be considered a bug - you want to check that things work _without_ the build dependency). The issue is that this is pretty EESSI-specific, since _we_ decide to demote CUDA to a build dep - that's not relevant for general EasyBuild. So... maybe it doesn't make sense to leave a breadcrumb here, and maybe _we_ (EESSI) should just make sure to have a hook that (re)loads CUDA in the sanity check stage.

The only alternative I see is to go for your approach _and then load the CUDA module listed in the dependency_ at the start of the sanity check step conditionally (i.e. if it isn't loaded yet), and if that happens, also unload it (under the same condition) at the end. I'm honestly not directly sure how to do that, though I'm sure EasyBuild framework has functions to load and unload modules :) Even then, it's a lot of complexity that is unnecessary for maintstream EasyBuild users - I'm not sure if I'd like to impose that, even if it doesn't _break_ anything for EB-only users either.

2025-05-12 15:50 UTC, casparvl commented on easybuild/framework/easyblock.py
> +        files_missing_devcode_but_has_ptx = []
Done in https://github.com/easybuilders/easybuild-framework/pull/4692/commits/2442d4491b1a9c224bdbbee63bc5a0d2ac605598

2025-05-12 15:51 UTC, casparvl commented on easybuild/framework/easyblock.py
> +                                fail_msg += ignore_msg
Ok, added a test case (1.a) that catches this _and_ fixed the actual issue (`ignore_msg` should have been defined at a higher level, so that it's also defined in this code path)

2025-05-12 15:51 UTC, casparvl commented on easybuild/framework/easyblock.py
> +        summary_msg_files = f"{len(files_missing_devcode)} files missing one or more CUDA compute capabilities: "
Fixed through https://github.com/easybuilders/easybuild-framework/commit/2442d4491b1a9c224bdbbee63bc5a0d2ac605598

2025-05-12 15:52 UTC, casparvl commented on easybuild/framework/easyblock.py
> +        summary_msg_files += f"These failures are ignored for {len(files_missing_devcode_ignored)} files: "
Fixed through https://github.com/easybuilders/easybuild-framework/commit/2442d4491b1a9c224bdbbee63bc5a0d2ac605598

2025-05-12 15:52 UTC, casparvl commented on easybuild/framework/easyblock.py
> +        summary_msg_files += f"Capabilities than requested: {files_additional_devcode}\n"
Fixed through https://github.com/easybuilders/easybuild-framework/commit/2442d4491b1a9c224bdbbee63bc5a0d2ac605598

2025-05-12 15:52 UTC, casparvl commented on easybuild/framework/easyblock.py
> +        summary_msg_files += f"These failures are ignored for {len(files_additional_devcode_ignored)} files: "
Fixed through https://github.com/easybuilders/easybuild-framework/commit/2442d4491b1a9c224bdbbee63bc5a0d2ac605598

2025-05-12 15:52 UTC, casparvl commented on easybuild/framework/easyblock.py
> +        summary_msg_files += f" Capability: {files_missing_ptx}\n"
Fixed through https://github.com/easybuilders/easybuild-framework/commit/2442d4491b1a9c224bdbbee63bc5a0d2ac605598

2025-05-12 15:52 UTC, casparvl commented on easybuild/framework/easyblock.py
> +        summary_msg_files += f"These failures are ignored for {len(files_missing_ptx_ignored)} files: "
Fixed through https://github.com/easybuilders/easybuild-framework/commit/2442d4491b1a9c224bdbbee63bc5a0d2ac605598

2025-05-12 15:58 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +            summary_msg += f"fails: {len(files_missing_devcode_fails)})\n"
Yes, mistake

2025-05-14 12:13 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +                        # case it is a warning)
```suggestion
                        #   case it is a warning)
```

2025-05-14 12:19 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +                                        # from, this is considerd a failure
```suggestion
                                        # from, this is considered a failure
```

2025-05-14 20:17 UTC, ocaisa requested changes
Will take it for a final test drive in the morning

2025-05-14 20:17 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +            trace_and_log(msg)
This is confusing, it seems the list is already in the log from 3711 below so only the first condition is needed (minus the `build_option` check)?
```suggestion
        if (
            len(files_missing_devcode) > 0 or len(files_additional_devcode) > 0 or len(files_missing_ptx) > 0
        ):
            trace_and_log("See build log for detailed lists of files not passing the CUDA Sanity Check")
```

2025-05-14 20:17 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +        if get_software_root('CUDA'):
You only need the CUDA module loaded so you have access to `cuobjdump`, and this is checked in the next line

2025-05-14 20:17 UTC, ocaisa commented on easybuild/tools/systemtools.py
> +
```suggestion
```

2025-05-15 13:50 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +        if get_software_root('CUDA'):
There is another scenario where this is a problem. LLVM can compile CUDA code and the sanity check should also run on that. I think that is out of scope for this PR, but how will we ever remember to add this later? An issue I suppose.

2025-05-15 14:15 UTC, ocaisa requested changes

2025-05-15 14:15 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +            trace_and_log("(not running with --cuda-sanity-check-fail-on-error, so not considered failures)")
```suggestion
            trace_and_log("(not running with --cuda-sanity-check-error-on-fail, so not considered failures)")
```

2025-05-15 14:15 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +            trace_and_log("(not running with --cuda-sanity-check-fail-on-error, so not considered failures)")
```suggestion
            trace_and_log("(not running with --cuda-sanity-check-error-on-fail, so not considered failures)")
```

2025-05-15 14:15 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +            trace_and_log("(not running with --cuda-sanity-check-fail-on-error, so not considered failures)")
```suggestion
            trace_and_log("(not running with --cuda-sanity-check-error-on-fail, so not considered failures)")
```

2025-05-15 14:38 UTC, ocaisa commented
I also found the scenario where the check is not executed (in the EESSI context):
```
eb CUDA-Samples-12.1-GCC-12.3.0-CUDA-12.1.1.eb --sanity-check --cuda-compute 8.0 --cuda-sanity-check-error-on-fail --cuda-sanity-check-accept-ptx-as-devcode
```
so it is clear that CUDA is loaded only in the case where the software is actually being built

2025-05-15 14:41 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +                raise EasyBuildError("Failed to execute CUDA sanity check: cuobjdump not found")
That suggestion is not correct, I'm working on it

2025-05-15 14:47 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +            self.log.debug("Skipping CUDA sanity check: CUDA module was not loaded")
```suggestion
        if 'CUDA' in [dep['name'] for dep in self.cfg.dependencies()]:
            if shutil.which('cuobjdump'):
                cuda_fails = self.sanity_check_cuda()
                if cuda_fails:
                    self.log.warning("CUDA device code sanity check failed!")
                    self.sanity_check_fail_msgs.extend(cuda_fails)
            else:
                msg = "Failed to execute CUDA sanity check: cuobjdump not found\n"
                msg += "CUDA module must be loaded for sanity check (or cuobjdump availabe in PATH)"
                raise EasyBuildError(msg)
        else:
            self.log.debug("Skipping CUDA sanity check: CUDA is not in dependencies")
```

2025-05-15 15:22 UTC, casparvl commented on easybuild/framework/easyblock.py
> +        if get_software_root('CUDA'):
> You only need the CUDA module loaded so you have access to cuobjdump, and this is checked in the next line

No, it's not just for that: you want to _avoid_ running the CUDA sanity check if you're not building CUDA software (as it can take quite some time if there are many files).

> LLVM can compile CUDA code and the sanity check should also run on that. 

I don't have experience with this, but would it mean you don't have a CUDA module loaded at all? Or does LLVM compile the code, but you're still using libraries from the CUDA module? I would expect the latter, no? And in that case, it's no problem...

2025-05-15 15:23 UTC, casparvl commented on easybuild/framework/easyblock.py
> +                raise EasyBuildError("Failed to execute CUDA sanity check: cuobjdump not found")
I'm... confused. If `shutil.which('cuobjdump')` fails to return anything, that means we've failed to find `cuobjdump`, and thus we've failed to execute the sanity check, right? What am I missing here? :)

2025-05-15 15:26 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            self.log.debug("Skipping CUDA sanity check: CUDA module was not loaded")
Ok, my earlier argument was actually false: I said you needed CUDA to be loaded for `cuobjdump`, but indeed, since that's a separate check, you can basically do what you are proposing and say:

```
# Do we need to run the CUDA sanity check? I.e. is this software that uses CUDA?
if 'CUDA' in [dep['name'] for dep in self.cfg.dependencies()]:
    # Do we have what we need to run the CUDA sanity check?
    if shutil.which('cuobjdump'):

I'm ok with that approach.

Note that your current suggestion

> "CUDA module must be loaded for sanity check (or cuobjdump availabe in PATH)"

Contained a typo ('availabe'), I corrected that by editing your suggestion.

2025-05-15 15:30 UTC, casparvl commented
> I also found the scenario where the check is not executed (in the EESSI context):
> 
> ```
> eb CUDA-Samples-12.1-GCC-12.3.0-CUDA-12.1.1.eb --sanity-check --cuda-compute 8.0 --cuda-sanity-check-error-on-fail --cuda-sanity-check-accept-ptx-as-devcode
> ```
> 
> so it is clear that CUDA is loaded only in the case where the software is actually being built

Right, so: it does not run if

1. you're using EESSI AND
2. you're running with `--sanity-check-only` (you were missing `-only`, but I suppose that's what you meant.

I think that's acceptable for now (i.e. shouldn't block the merge), as it doesn't affect main EB users.

2025-05-15 15:32 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            self.log.debug("Skipping CUDA sanity check: CUDA module was not loaded")
I'm going to commit this suggestion, I think it's good.

2025-05-15 15:41 UTC, casparvl commented
> I ran
> 
> ```
> eb CUDA-Samples-12.1-GCC-12.3.0-CUDA-12.1.1.eb --rebuild --cuda-compute 8.0 --cuda-sanity-check-error-on-fail --cuda-sanity-check-accept-ptx-as-devcode
> ```
> 
> and the error is indeed a huge wall of text. Some of this should just be in the log.

It is a wall of text _if_ there are a lot of files failing to pass the check. But, I agree, that might not be very nice.

Maybe it's better to change things like:

```
                              if is_failure:
                                    fail_msgs.append(fail_msg)
                                else:
                                    self.log.warning(fail_msg)
```
so that it unconditionally logs to a warning. Then, we make some way to count failures (we can probably just add up all the length of all the `*_fails` file lists) And then, we use the 'is_failure' at the end to do:

```
if is_failure:
    return f"{num_failures} files failed to pass the CUDA sanity check. See build log for details."
else
    return ""
```

I probably don't have time today to implement that though (maybe this evening, but not sure). If you have a change to look at it just ping me on Slack that you're working on it so we don't do duplicate work.

2025-05-16 08:20 UTC, ocaisa approved these changes
I've tested this a bunch and I am quite happy with the user experience now.

2025-05-16 09:17 UTC, ocaisa commented
Thanks a lot @jfgrimm for seeding this and @casparvl for getting it over the line, I think this is of high value

2025-05-16 10:00 UTC, boegel commented
`test_toy_cuda_sanity_check` is failing with:
```
easybuild.tools.build_log.EasyBuildError: "Installation of CUDA-5.5.22.eb failed: 'cuda_5.5.22_linux_64.run has unknown file extension'"
```

2025-05-16 10:59 UTC, boegel commented on easybuild/framework/easyblock.py
> +            cuda_dirs = DEFAULT_BIN_LIB_SUBDIRS
We're currently only checking files in `bin` and `lib` basically, but there may be additional files to check, for example `.so` files in `lib/python*/site-packages`, like:

```
$ cuobjdump /software/Uni-Core/0.0.3-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/unicore_fused_adam.cpython-311-x86_64-linux-gnu.so

Fatbin elf code:
================
arch = sm_70
code version = [1,7]
host = linux
compile_size = 64bit

Fatbin ptx code:
================
arch = sm_70
code version = [8,1]
host = linux
compile_size = 64bit
compressed
```

Not checking those is a bug strictly speaking, but I'm fine with if we tackle that in a follow-up PR (since there's a couple of options there to fix this I think).

2025-05-16 11:03 UTC, boegel commented on easybuild/framework/easyblock.py
> +            cuda_dirs = DEFAULT_BIN_LIB_SUBDIRS
In same cases it's even deeper.

For PyTorch for example:

```
/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so
```

2025-05-16 11:05 UTC, boegel commented on easybuild/framework/easyblock.py
> +        ignore_file_list = [os.path.join(self.installdir, d) for d in self.cfg['cuda_sanity_ignore_files']]
@casparvl Let's open an issue on this to follow-up on this?

2025-05-16 11:06 UTC, boegel commented on easybuild/framework/easyblock.py
> +        ignore_file_list = [os.path.join(self.installdir, d) for d in self.cfg['cuda_sanity_ignore_files']]
done, see:
* #4882

2025-05-16 11:17 UTC, ocaisa commented on easybuild/framework/easyblock.py
> +            cuda_dirs = DEFAULT_BIN_LIB_SUBDIRS
In fact we discussed this already, and @casparvl deliberately only did exactly what is checked by the rpath sanity check. If we do a follow up for this PR, we should include the rpath check in that.

2025-05-16 11:20 UTC, ocaisa commented
> `test_toy_cuda_sanity_check` is failing with:
> 
> ```
> easybuild.tools.build_log.EasyBuildError: "Installation of CUDA-5.5.22.eb failed: 'cuda_5.5.22_linux_64.run has unknown file extension'"
> ```

This easyconfig is not installed anywe

2025-05-16 11:25 UTC, ocaisa commented
> `test_toy_cuda_sanity_check` is failing with:
> 
> ```
> easybuild.tools.build_log.EasyBuildError: "Installation of CUDA-5.5.22.eb failed: 'cuda_5.5.22_linux_64.run has unknown file extension'"
> ```

I think this is only failing some scenarios because a HMNS is being used (which means the easyconfig has to be parsed)

2025-05-16 11:51 UTC, ocaisa commented on test/framework/toy_build.py
> +        cuda_mod_dir = os.path.join(module_dir, 'CUDA')
Should we remove this again after?

2025-05-16 12:04 UTC, casparvl commented on easybuild/framework/easyblock.py
> +            cuda_dirs = DEFAULT_BIN_LIB_SUBDIRS
So, I guess we're actually also _not_ doing an `RPATH` sanity check on any lib in a python package... I never realized. Definitely requires improvements - but not just for the CUDA sanity check, also for the RPATH sanity check. And... at some point we might need to think about optimization of this step - it already takes a minute for CUDA-samples, and that only has 130 or so CUDA files. I guess we could run things in parallel based on the configured parallelism for EasyBuild, though it would require the list appending to be done atomically. Not a huge deal, since most execution time is probably in executing the `cuobjdump` output. Plus, I wonder if there are faster ways to figure out _if_ something is a CUDA binary that are maybe more lightweight than `cuobjdump`. That might also speed things up.

Anyway, one thing at a time...

2025-05-16 12:29 UTC, boegel commented on easybuild/framework/easyblock.py
> +            cuda_dirs = DEFAULT_BIN_LIB_SUBDIRS
Yeah, good point, this is probably also not covered by the RPATH sanity check, that's worth opening an issue for:
* #4883

2025-05-16 13:07 UTC, boegel commented on easybuild/framework/easyblock.py
> +            cuda_dirs = DEFAULT_BIN_LIB_SUBDIRS
I managed to ensure that shared libraries under `lib/python*/site-packages` are also covered, I have that implementation working.

May be worth including this in here, I'll open a separate PR for that (as soon as https://github.com/jfgrimm/easybuild-framework/pull/2 is merged)

2025-05-16 17:10 UTC, ocaisa commented
Looks like failing test is yet another issue with rate limits:

* https://github.com/easybuilders/easybuild-framework/blob/76e9033bc0c7a2c8c2f751eed69df7cb1887857a/test/framework/filetools.py#L525

2025-05-16 17:45 UTC, ocaisa commented
@boegel Good to go now

2025-05-20 18:42 UTC, boegel approved these changes
This is a big change, implementing a big enhancement to the sanity check step performed by EasyBuild for builds of GPU software (anything that involves `CUDA` as a direct dependency).

It's been extensively tested and reviewed by several people, so time to get this in (still in time for the upcoming EasyBuild v5.1.0 release)!

@jfgrimm Thanks a lot for kickstarting this, and thanks for @casparvl and @ocaisa for all the work that was done on this in recent weeks!

2025-05-20 18:42 UTC, merged

2025-05-21 08:34 UTC, Flamefire commented on easybuild/framework/easyblock.py
> +                        self.log.debug("Sanity checking file {path} for CUDA device code")
This message is duplicate isn't it?

2025-05-21 08:53 UTC, Flamefire commented on easybuild/tools/systemtools.py
> +        if not shutil.which('cuobjdump'):
This is already checked at https://github.com/easybuilders/easybuild-framework/pull/4692/files#diff-00260ae7a519d5825760f53b067b29fb84a3e0d2649e6a27ace99abaca96d7d1R4361 is this required in both places?