fix handling of quotes in rpath wrapper
easybuilders/easybuild-framework pull request #4722
Opened 2024-12-12 11:06 UTC by Flamefire

In some software the compiler must be invoked with an argument containing a literal single quote which requires escaping in the call. E.g.: `gcc -DFOO=\'value\'`

However the current rpath wrapper would remove those single quotes causing errors during compilation or erronous behavior of the compiled binary.

Fix by replacing the `eval` of the `rpath_args.py` output by `readarray -t`. An array asignment could be used (`CMD_ARGS=( $(rpath_args.py ...) )`) but that would break up arguments containing spaces. Quotes from the output are kept literally, so quoting to avoid this is not possible. `readarray -t` works and is widely available.

Also some minor fixes related to quoting in the bash script template.

2025-09-03 16:37 UTC, boegel commented
@Flamefire Failing tests should be looked into, and meanwhile merge conflicts have emerged as well

2025-09-04 08:08 UTC, Flamefire commented
Resolved the merge conflicts. Test failures were mostly due to `--trace` output of `run_shell_cmd`.

I also switched the separator to NULL similar to `find -print0` to make it (even more) robust

2025-10-07 14:05 UTC, Flamefire commented
Shall we add a special case to tests to detect the GitHub rate limit and skip/succeed them in PRs?

2026-09-09 13:39 UTC, Thyre commented on easybuild/scripts/rpath_wrapper_template.sh.in
> -TOPDIR=`dirname $0`
The removal of `TOPDIR` causes the wrappers to fail, because they cannot find the `rpath_args.py` script anymore.

From e.g. `buildenv/default` for `foss/2025b`
```
# rpath_args.py script spits out statement that defines $CMD_ARGS
# options for 'python' command (see https://docs.python.org/3/using/cmdline.html#miscellaneous-options)
# * -I: isolated mode: ignore all $PYTHON* environment variables (like $PYTHONPATH) and user site-packages directory
# * -O: run Python in optimized mode (remove asserts, ignore stuff under __debug__ guard);
# * -S: disable the import of the module site and the site-dependent manipulations of sys.path that it entails;
log "$PYTHON_EXE -I -O -S ${TOPDIR}/../rpath_args.py '$CMD' '/lib.*,/usr.*,/tmp/eb-fmu9zyhx.*,/data/EasyBuild-develop/build/buildenv/default/foss-2025b.*,.*/lib(64)?/stubs/?.*,.*/stubs/lib(64)?/?.*' '/data/EasyBuild-develop/software/buildenv/default-foss-2025b/lib,/data/EasyBuild-develop/software/buildenv/default-foss-2025b/lib64,$ORIGIN,$ORIGIN/../lib,$ORIGIN/../lib64' $*"
readarray -d '' -t CMD_ARGS < <( "$PYTHON_EXE" -I -O -S '${TOPDIR}/../rpath_args.py' "$CMD" '/lib.*,/usr.*,/tmp/eb-fmu9zyhx.*,/data/EasyBuild-develop/build/buildenv/default/foss-2025b.*,.*/lib(64)?/stubs/?.*,.*/stubs/lib(64)?/?.*' '/data/EasyBuild-develop/software/buildenv/default-foss-2025b/lib,/data/EasyBuild-develop/software/buildenv/default-foss-2025b/lib64,$ORIGIN,$ORIGIN/../lib,$ORIGIN/../lib64' "$@" )
```

Trying to run the wrapper yields:

```
python3: can't open file '/home/jreuter/Projects/EasyBuild/JSC/Golden_Repo/h/helix/${TOPDIR}/../rpath_args.py': [Errno 2] No such file or directory
```

2026-09-09 13:42 UTC, Thyre commented on easybuild/scripts/rpath_wrapper_template.sh.in
> +readarray -d '' -t CMD_ARGS < <( "$PYTHON_EXE" -I -O -S '%(rpath_args_py)s' "$CMD" '%(rpath_filter)s' '%(rpath_include)s' "$@" )
```suggestion
readarray -d '' -t CMD_ARGS < <( "$PYTHON_EXE" -I -O -S "%(rpath_args_py)s" "$CMD" '%(rpath_filter)s' '%(rpath_include)s' "$@" )
```

Single quotes do not evaluate `$TOPDIR`

2026-09-09 13:53 UTC, Thyre commented
With the changes mentioned above, I was able to compile the test case failing in https://github.com/easybuilders/easybuild-framework/issues/5192. Maybe we should explicitly test for this as well.

I'll close https://github.com/easybuilders/easybuild-framework/pull/5261

2026-09-09 14:04 UTC, boegel commented on easybuild/scripts/rpath_wrapper_template.sh.in
> -TOPDIR=`dirname $0`
How is this not caught by the tests we have in framework test suite? 🤔

2026-09-09 14:18 UTC, Thyre commented on easybuild/scripts/rpath_wrapper_template.sh.in
> -TOPDIR=`dirname $0`
That's a good question!
I encountered this issue with the `buildenv` module. Here, `$TOPDIR` is used. The RPATH wrappers generated by `--rpath` do not use this variable, but instead hard-code the path from EasyBuild. Hence, the normal wrappers do not fail, but `buildenv` does.

Here e.g. while building `M4-1.4.21.eb`:
```
# rpath_args.py script spits out statement that defines $CMD_ARGS
# options for 'python' command (see https://docs.python.org/3/using/cmdline.html#miscellaneous-options)
# * -I: isolated mode: ignore all $PYTHON* environment variables (like $PYTHONPATH) and user site-packages directory
# * -O: run Python in optimized mode (remove asserts, ignore stuff under __debug__ guard);
# * -S: disable the import of the module site and the site-dependent manipulations of sys.path that it entails;
log "$PYTHON_EXE -I -O -S /data/EasyBuild/easybuild/scripts/rpath_args.py '$CMD' '/lib.*,/usr.*,/tmp/eb-qnmvf_89.*,/data/EasyBuild-develop/build/M4/1.4.21/system-system.*,.*/lib(64)?/stubs/?.*,.*/stubs/lib(64)?/?.*' '/tmp/software/M4/1.4.21/lib,/tmp/software/M4/1.4.21/lib64,$ORIGIN,$ORIGIN/../lib,$ORIGIN/../lib64' $*"
readarray -d '' -t CMD_ARGS < <( "$PYTHON_EXE" -I -O -S '/data/EasyBuild/easybuild/scripts/rpath_args.py' "$CMD" '/lib.*,/usr.*,/tmp/eb-qnmvf_89.*,/data/EasyBuild-develop/build/M4/1.4.21/system-system.*,.*/lib(64)?/stubs/?.*,.*/stubs/lib(64)?/?.*' '/tmp/software/M4/1.4.21/lib,/tmp/software/M4/1.4.21/lib64,$ORIGIN,$ORIGIN/../lib,$ORIGIN/../lib64' "$@" )

```

2026-09-09 16:44 UTC, boegel commented on easybuild/scripts/rpath_wrapper_template.sh.in
> -TOPDIR=`dirname $0`
Ah, yes, indeed, there's an explicit assumption that `$TOPDIR` is defined, and it only matters when the RPATH wrappers are being copied to be used outside of EasyBuild, see https://github.com/easybuilders/easybuild-framework/blob/ce087b53de0431502780ca7040bdca2a2e9fa076/easybuild/tools/toolchain/toolchain.py#L1074-L1082

2026-09-09 16:47 UTC, boegel commented on easybuild/scripts/rpath_wrapper_template.sh.in
> +CMD=$(basename "$0")
We need to keep the definition of `TOPDIR`, we rely that the RPATH wrapper script sets it in `Toolchain.prepare_rpath_wrappers`:

```suggestion
CMD=$(basename "$0")
# $TOPDIR is not used in this template script, but Toolchain.prepare_rpath_wrappers assumes it is set
# so it can be used as an anchor to determine the path to the rpath_args.py script
TOPDIR=$(dirname "$0")

2026-09-09 17:57 UTC, boegel requested changes

2026-09-09 17:57 UTC, boegel commented on easybuild/scripts/rpath_wrapper_template.sh.in
>  # rpath_args.py script spits out statement that defines $CMD_ARGS
comment is no longer correct, rpath_args.py doesn't define `$CMD_ARGS` anymore

2026-09-09 17:57 UTC, boegel commented on easybuild/scripts/rpath_wrapper_template.sh.in
> +readarray -d '' -t CMD_ARGS < <( "$PYTHON_EXE" -I -O -S '%(rpath_args_py)s' "$CMD" '%(rpath_filter)s' '%(rpath_include)s' "$@" )
Hmm, this should also have been caught by the tests, along with removing `$TOPDIR` causing trouble, so we have a clear gap in our tests...

I'll take a look and see if I can come up with something that would have caught this...

2026-09-09 17:57 UTC, boegel commented on easybuild/scripts/rpath_args.py
> +print('\0'.join(cmd_args), end='')
```suggestion
# use null character (\0) as separator, so we can do a clean split again (in RPATH wrapper shell script)
print('\0'.join(cmd_args), end='')

2026-09-09 17:57 UTC, boegel commented on easybuild/scripts/rpath_wrapper_template.sh.in
> +log "$PYTHON_EXE -I -O -S %(rpath_args_py)s '$CMD' '%(rpath_filter)s' '%(rpath_include)s' $*"
line below can use a comment, since `readarray` isn't that common, and there's an assumption made on what `rpath_args.py` produces exactly...

```suggestion
log "$PYTHON_EXE -I -O -S %(rpath_args_py)s '$CMD' '%(rpath_filter)s' '%(rpath_include)s' $*"
# use readarray to process output obtained from rpath_args.py script,
# store resulting array in $CMD_ARGS;
# -d '' specifies that splitting should be done by null character ('\0' in rpath_args.py),
# -t specifies that delimiters themselves must be removed

2026-09-09 17:57 UTC, boegel commented on easybuild/tools/toolchain/toolchain.py
> +        return b"rpath_args.py '$CMD'" in read_file(path, mode='rb')
This looks incorrect now, taking into account the changes made to `easybuild/scripts/rpath_wrapper_template.sh.in`, since i) the path to `rpath_args.py` is wrapper in single quotes, ii) `$CMD` is surrounded by double quotes

```suggestion
        return rb'rpath_args.py\' "$CMD"' in read_file(path, mode='rb')

2026-09-09 17:59 UTC, boegel commented on easybuild/scripts/rpath_wrapper_template.sh.in
> +readarray -d '' -t CMD_ARGS < <( "$PYTHON_EXE" -I -O -S '%(rpath_args_py)s' "$CMD" '%(rpath_filter)s' '%(rpath_include)s' "$@" )
applied suggested fix in ce8ca459f267bc91f5baff5ef7c0190a9fa5e872 (along with a corresponding fix for `test_toy_rpath`)

2026-09-09 18:00 UTC, boegel commented on easybuild/scripts/rpath_wrapper_template.sh.in
> -TOPDIR=`dirname $0`
restored defining of `TOPDIR` in ce8ca459f267bc91f5baff5ef7c0190a9fa5e872

2026-09-09 18:00 UTC, boegel commented on easybuild/scripts/rpath_wrapper_template.sh.in
> +CMD=$(basename "$0")
fixed in ce8ca459f267bc91f5baff5ef7c0190a9fa5e872

2026-09-09 18:01 UTC, boegel commented on easybuild/scripts/rpath_wrapper_template.sh.in
>  # rpath_args.py script spits out statement that defines $CMD_ARGS
fixed in ce8ca459f267bc91f5baff5ef7c0190a9fa5e872

2026-09-09 18:01 UTC, boegel commented on easybuild/scripts/rpath_args.py
> +print('\0'.join(cmd_args), end='')
fixed in ce8ca459f267bc91f5baff5ef7c0190a9fa5e872

2026-09-09 18:01 UTC, boegel commented on easybuild/tools/toolchain/toolchain.py
> +        return b"rpath_args.py '$CMD'" in read_file(path, mode='rb')
fixed in ce8ca459f267bc91f5baff5ef7c0190a9fa5e872

2026-09-09 18:01 UTC, boegel commented on easybuild/scripts/rpath_wrapper_template.sh.in
> +log "$PYTHON_EXE -I -O -S %(rpath_args_py)s '$CMD' '%(rpath_filter)s' '%(rpath_include)s' $*"
fixed in ce8ca459f267bc91f5baff5ef7c0190a9fa5e872

2026-09-09 20:13 UTC, boegel commented
@Thyre Can you take this for a quick spin again, before we proceed with merging?

2026-09-10 06:16 UTC, Flamefire commented on easybuild/scripts/rpath_wrapper_template.sh.in
> -TOPDIR=`dirname $0`
I found `test_toolchain_prepare_rpath_external` which is supposed to check this case:
Instead of putting in the path it puts in a relative path:
```
<root>
  rpath.py
  cxx_wrapper
     cxx.sh -> call ../rpath.py
```

I'm not really sure why it is done that way: Why not put the full path in there?

Anyway enhanced the test to actually test this use case works. Previously it just tested if the compiler wrapper was created.

2026-09-10 06:48 UTC, Flamefire commented
I had a full test and fix prepared that catches the case when the relative path didn't work. I incorporated the remaining parts of your commit @boegel 

> Maybe we should explicitly test for this as well.

Makes sense and should be easy to do. Checking

2026-09-10 08:07 UTC, Thyre commented
> @Thyre Can you take this for a quick spin again, before we proceed with merging?

Building the test case still works fine :+1:

2026-09-10 08:10 UTC, Flamefire commented
> With the changes mentioned above, I was able to compile the test case failing in https://github.com/easybuilders/easybuild-framework/issues/5192. Maybe we should explicitly test for this as well.

`test_toolchain_prepare_rpath` already did contain a "dry" test for that
```
            r'-DX1="\"\""',
            r'-DX2="\"I\""',
            r"-DY1=\'\'",
            r"-DY2=\'J\'",
```

I added a real test using the host systems compiler and an actual C source.
We already rely on the `gcc` host compiler for the toy builds so this only raises the requirement to GCC 4.7 as the test requires C++11

2026-09-10 08:10 UTC, Flamefire commented
@Thyre Was this with my commits from today included? Minor change but just to be sure

2026-09-10 08:12 UTC, Thyre commented
> @Thyre Was this with my commits from today included? Minor change but just to be sure

Yes, it should include https://github.com/easybuilders/easybuild-framework/pull/4722/changes/31dd7d51d1a62c5d2ce934c926cc02bdeb0c1cfa and anything before that.

2026-09-10 10:07 UTC, boegel commented
enhanced `test_toolchain_prepare_rpath_external` now indeed catches the problem where `$TOPDIR` is not defined, as follows:
```
FAIL: test_toolchain_prepare_rpath_external (test.framework.toolchain.ToolchainTest)
Test toolchain.prepare under --rpath with rpath_wrappers_dir argument
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/vsc40023/easybuild-framework/test/framework/toolchain.py", line 3281, in test_toolchain_prepare_rpath_external
    self.assertEqual(out, ['-Wl,--disable-new-dtags', f'-Wl,-rpath={foo_path}', f'-L{foo_path}'])
  File "/tmp/vsc40023/easybuild-framework/easybuild/base/testing.py", line 114, in assertEqual
    raise AssertionError("%s:\nDIFF%s:\n%s" % (msg, limit, ''.join(diff[:self.ASSERT_MAX_DIFF]))) from None
AssertionError: Lists differ: ["/usr/bin/python3: can't open file '/../r[47 chars]ory"] != ['-Wl,--disable-new-dtags', '-Wl,-rpath=/t[89 chars]foo']

First differing element 0:
"/usr/bin/python3: can't open file '/../r[46 chars]tory"
'-Wl,--disable-new-dtags'

Second list contains 2 additional elements.
First extra element 1:
'-Wl,-rpath=/tmp/eb-aw32plqj/eb-v6v_bgpz/eb-eus7jfbq/foo'

- ["/usr/bin/python3: can't open file '/../rpath_args.py': [Errno 2] No such "
-  'file or directory']
+ ['-Wl,--disable-new-dtags',
+  '-Wl,-rpath=/tmp/eb-aw32plqj/eb-v6v_bgpz/eb-eus7jfbq/foo',
+  '-L/tmp/eb-aw32plqj/eb-v6v_bgpz/eb-eus7jfbq/foo']:
DIFF:
- ["/usr/bin/python3: can't open file '/../rpath_args.py': [Errno 2] No such "
-  'file or directory']+ ['-Wl,--disable-new-dtags',
+  '-Wl,-rpath=/tmp/eb-aw32plqj/eb-v6v_bgpz/eb-eus7jfbq/foo',
+  '-L/tmp/eb-aw32plqj/eb-v6v_bgpz/eb-eus7jfbq/foo']

----------------------------------------------------------------------
Ran 1 test in 0.413s

FAILED (failures=1)
```

(that only fails if I remove the `TOPDIR=` line again from `easybuild/scripts/rpath_wrapper_template.sh.in`, of course)

It's bit a bit hard to notice at first, but the `can't open file '/../rpath_args.py'` at least point in the right direction...

2026-09-10 10:41 UTC, boegel approved these changes
lgtm

2026-09-10 11:14 UTC, merged